export const KNOWLEDGE_BASE_UPDATED_AT = "2026-09-26";

export const ROLE_FILTERS = [
  { id: "all", label: "All Roles" },
  { id: "manager", label: "Manager" },
  { id: "kitchen", label: "Kitchen" },
  { id: "inventory", label: "Inventory" },
  { id: "cashier", label: "Cashier" },
];

export const KNOWLEDGE_CATEGORIES = [
  { id: "kitchen", name: "Kitchen", count: 12, icon: "chef" },
  { id: "inventory", name: "Inventory", count: 8, icon: "boxes" },
  { id: "food-safety", name: "Food Safety", count: 10, icon: "shield", tone: "safety" },
  { id: "orders-pos", name: "Orders & POS", count: 7, icon: "monitor" },
  { id: "customers-rewards", name: "Customers & Rewards", count: 9, icon: "users" },
  { id: "admin-settings", name: "Admin & Settings", count: 6, icon: "settings" },
  { id: "cleaning-hygiene", name: "Cleaning & Hygiene", count: 8, icon: "sparkles" },
  { id: "emergency", name: "Emergency", count: 6, icon: "triangle", tone: "critical" },
];

export const TIP_OF_THE_DAY = {
  title: "Label every opened item.",
  description: "Record the opened date, use-by date, and batch on all opened food items. This helps keep food safe, reduces waste, and makes tracking easier.",
  image: "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1400&q=85",
  imageAlt: "Prepared ingredients stored in organized food containers",
};

export const KNOWLEDGE_GUIDES = [
  {
    id: "receive-stock",
    slug: "receive-stock-correctly",
    title: "Receive Stock Correctly",
    description: "Step-by-step receiving checks for deliveries, quantities, batches, and supporting records.",
    category: "inventory",
    type: "SOP",
    roles: ["admin", "manager", "inventory", "storekeeper"],
    keywords: ["supplier", "delivery", "purchase order", "batch", "stock in"],
    readingTime: 8,
    isPinned: true,
    isCritical: false,
    lastUpdated: "2026-09-26",
    relatedRoute: "/inventory/stock-in",
    icon: "boxes",
    sections: [
      { heading: "Before accepting", body: "Match the supplier and purchase reference, inspect the delivery condition, and confirm that the receiving record belongs to the correct order." },
      { heading: "Record accurately", body: "Enter accepted quantities, batch or lot details, expiry information, and unit cost from the approved supplier document. Note rejected or short quantities." },
      { heading: "Finish the receipt", body: "Review the stock movement before completing the receipt and escalate any mismatch through the purchasing workflow." },
    ],
  },
  {
    id: "fridge-storage",
    slug: "fridge-storage-guide",
    title: "Fridge Storage Guide",
    description: "Approved storage organization, labeling, separation, and escalation practices.",
    category: "food-safety",
    type: "Important",
    roles: ["admin", "manager", "kitchen", "inventory", "storekeeper"],
    keywords: ["fridge", "cold storage", "labels", "food safety", "temperature chart"],
    readingTime: 6,
    isPinned: true,
    isCritical: true,
    lastUpdated: "2026-09-25",
    relatedRoute: null,
    icon: "clipboard",
    sections: [
      { heading: "Use the approved chart", body: "Follow the restaurant-approved temperature and storage chart posted at the station. This guide intentionally does not replace approved safety limits." },
      { heading: "Store and label", body: "Keep products separated as required, use clean covered containers, and make every label readable before placing an item into storage." },
      { heading: "Escalate concerns", body: "Quarantine questionable items and report food-safety concerns to the responsible manager immediately." },
    ],
  },
  {
    id: "fefo-labeling",
    slug: "fefo-labeling-rules",
    title: "FEFO & Labeling Rules",
    description: "First Expired, First Out rotation and consistent labels for traceable stock.",
    category: "inventory",
    type: "SOP",
    roles: ["admin", "manager", "kitchen", "inventory", "storekeeper"],
    keywords: ["first expired first out", "expiry", "batch", "label", "rotation"],
    readingTime: 7,
    isPinned: true,
    isCritical: false,
    lastUpdated: "2026-09-24",
    relatedRoute: "/inventory/expiry-tracking",
    icon: "tag",
    sections: [
      { heading: "Rotate by expiry", body: "Arrange usable stock so the batch expiring first is selected first. Do not substitute FIFO where expiry dates determine safe rotation." },
      { heading: "Label every opened item", body: "Record the opened date, approved use-by date, batch reference, and staff identification according to the restaurant SOP." },
      { heading: "Review exceptions", body: "Separate unreadable, damaged, expired, or questionable items and use the approved waste or manager-review process." },
    ],
  },
  {
    id: "physical-count",
    slug: "physical-inventory-count",
    title: "Physical Inventory Count",
    description: "A controlled process for counting stock and reviewing variances before approval.",
    category: "inventory",
    type: "SOP",
    roles: ["admin", "manager", "inventory", "storekeeper"],
    keywords: ["inventory count", "variance", "blind count", "stock"],
    readingTime: 6,
    isPinned: true,
    isCritical: false,
    lastUpdated: "2026-09-23",
    relatedRoute: "/inventory/inventory-count",
    icon: "chart",
    sections: [
      { heading: "Prepare", body: "Finish pending stock movements where practical, organize the count area, and confirm the scope before starting." },
      { heading: "Count consistently", body: "Use each inventory item's configured base unit and enter the observed quantity without altering system stock directly." },
      { heading: "Review and approve", body: "Investigate material variances and let an authorized reviewer complete the audited adjustment workflow." },
    ],
  },
  {
    id: "opening-checklist",
    slug: "opening-checklist",
    title: "Opening Checklist",
    description: "Daily setup, equipment checks, station readiness, and operational handover.",
    category: "kitchen",
    type: "Checklist",
    roles: ["admin", "manager", "kitchen", "cashier"],
    keywords: ["opening", "daily", "setup", "equipment", "cashier"],
    readingTime: 4,
    isPinned: true,
    isCritical: false,
    lastUpdated: "2026-09-22",
    relatedRoute: null,
    icon: "sun",
    sections: [
      { heading: "Start safely", body: "Complete personal readiness and area checks, then report damaged equipment or unresolved safety concerns before service." },
      { heading: "Prepare the station", body: "Confirm approved stock, labels, tools, and cleaning supplies are ready for the assigned station." },
      { heading: "Confirm handover", body: "Record outstanding issues and confirm the manager or shift lead has reviewed them." },
    ],
  },
  {
    id: "closing-checklist",
    slug: "closing-checklist",
    title: "Closing Checklist",
    description: "End-of-day cleaning, stock protection, shutdown, and security handover.",
    category: "cleaning-hygiene",
    type: "Checklist",
    roles: ["admin", "manager", "kitchen", "cashier"],
    keywords: ["closing", "cleaning", "shutdown", "handover", "security"],
    readingTime: 6,
    isPinned: true,
    isCritical: false,
    lastUpdated: "2026-09-22",
    relatedRoute: null,
    icon: "moon",
    sections: [
      { heading: "Protect stock", body: "Label, cover, store, or record waste for all remaining items using the restaurant-approved process." },
      { heading: "Clean and shut down", body: "Complete the assigned cleaning schedule and equipment shutdown checklist without bypassing safety instructions." },
      { heading: "Handover", body: "Document exceptions, secure the area, and confirm completion with the shift lead." },
    ],
  },
  {
    id: "cleaning-schedule",
    slug: "updated-cleaning-schedule",
    title: "Updated Cleaning Schedule",
    description: "Revised responsibilities and grill deep-cleaning handover steps.",
    category: "cleaning-hygiene",
    type: "Checklist",
    roles: ["admin", "manager", "kitchen"],
    keywords: ["cleaning", "hygiene", "schedule", "grill"],
    readingTime: 5,
    isPinned: false,
    isCritical: false,
    lastUpdated: "2026-09-26",
    relatedRoute: null,
    icon: "sparkles",
    updateSummary: "Revised responsibilities and added grill deep-cleaning handover steps.",
    updateStatus: "Updated",
    sections: [{ heading: "Use the current schedule", body: "Follow the latest assigned cleaning schedule and record incomplete tasks for the next shift and manager review." }],
  },
  {
    id: "temperature-chart",
    slug: "food-safety-temperature-chart",
    title: "Food Safety: Temperature Chart",
    description: "How to use and escalate against the restaurant-approved temperature chart.",
    category: "food-safety",
    type: "Important",
    roles: ["admin", "manager", "kitchen", "inventory", "storekeeper"],
    keywords: ["food safety", "temperature", "chart", "fridge"],
    readingTime: 5,
    isPinned: false,
    isCritical: true,
    lastUpdated: "2026-09-25",
    relatedRoute: null,
    icon: "shield",
    updateSummary: "Clarified how staff should use the approved internal temperature chart.",
    updateStatus: "Updated",
    sections: [{ heading: "Owner approval required", body: "Exact temperature limits must come from the restaurant-approved food-safety chart and applicable authority guidance; they are not duplicated here." }],
  },
  {
    id: "order-issues",
    slug: "order-issue-handling",
    title: "Order Issue Handling",
    description: "A consistent escalation path for incorrect, delayed, cancelled, or disputed orders.",
    category: "orders-pos",
    type: "Important",
    roles: ["admin", "manager", "cashier", "kitchen"],
    keywords: ["order", "refund", "cancel", "delay", "customer issue"],
    readingTime: 6,
    isPinned: false,
    isCritical: false,
    lastUpdated: "2026-09-24",
    relatedRoute: "/admin?tab=orders",
    icon: "cart",
    updateSummary: "Added escalation steps for third-party delivery and payment issues.",
    updateStatus: "New",
    sections: [{ heading: "Record before acting", body: "Confirm the order source and current payment state, record the issue clearly, and use the authorized cancellation or refund workflow." }],
  },
  {
    id: "customer-recovery",
    slug: "customer-service-recovery",
    title: "Customer Service Recovery",
    description: "Listen, document, and escalate customer concerns consistently.",
    category: "customers-rewards",
    type: "Guide",
    roles: ["admin", "manager", "cashier"],
    keywords: ["customer", "complaint", "rewards", "service"],
    readingTime: 5,
    isPinned: false,
    isCritical: false,
    lastUpdated: "2026-09-21",
    relatedRoute: null,
    icon: "users",
    sections: [{ heading: "Listen and document", body: "Acknowledge the concern, verify the order or account context, and document only the operational information needed for follow-up." }],
  },
  {
    id: "settings-review",
    slug: "settings-change-review",
    title: "Settings Change Review",
    description: "Review operational impact before saving shared restaurant settings.",
    category: "admin-settings",
    type: "Guide",
    roles: ["admin", "manager"],
    keywords: ["admin", "settings", "audit", "notifications"],
    readingTime: 4,
    isPinned: false,
    isCritical: false,
    lastUpdated: "2026-09-20",
    relatedRoute: "/admin?tab=settings",
    icon: "settings",
    sections: [{ heading: "Review shared impact", body: "Confirm how a settings change affects public ordering, POS, kitchen alerts, receipts, and inventory before saving it." }],
  },
  {
    id: "emergency-basics",
    slug: "emergency-response-basics",
    title: "Emergency Response Basics",
    description: "Stop work, protect people, and follow the approved emergency contact plan.",
    category: "emergency",
    type: "Important",
    roles: ["admin", "manager", "cashier", "kitchen", "inventory", "storekeeper", "accountant"],
    keywords: ["emergency", "incident", "safety", "report"],
    readingTime: 4,
    isPinned: false,
    isCritical: true,
    lastUpdated: "2026-09-19",
    relatedRoute: null,
    icon: "triangle",
    sections: [{ heading: "Follow the approved plan", body: "Prioritize immediate safety, notify the responsible manager, and use the posted emergency contacts and site procedure. This guide does not replace emergency services or approved instructions." }],
  },
];

export const CRITICAL_NOTES = [
  "Check fridge temperatures every 4 hours",
  "Report any food safety issues immediately",
];

export const RECENT_UPDATE_IDS = ["cleaning-schedule", "temperature-chart", "order-issues"];
export const DEFAULT_RECENT_GUIDE_IDS = ["temperature-chart", "cleaning-schedule", "physical-count", "order-issues"];
