import mongoose from "mongoose";
import Counter from "../models/Counter.js";
import { getRiyadhCreationYear } from "./expenseNumberService.js";
import { addRecordSearchIndexes } from "../utils/recordSearchIndexes.js";

export const RECORD_NUMBERS = Object.freeze({
  Refund: { field: "refundNumber", prefix: "RFN", annual: true },
  SupplierPayment: { field: "paymentNumber", prefix: "PAY", annual: true },
  PosShift: { field: "shiftNumber", prefix: "PSH", annual: true },
  CashMovement: { field: "movementNumber", prefix: "CSH", annual: true },
  StockTransaction: { field: "transactionNumber", prefix: "STX", annual: true },
  PosHeldSale: { field: "heldSaleNumber", prefix: "HLD", annual: true },
  Customer: { model: "User", field: "customerNumber", prefix: "CUS", filter: { role: "customer" } },
  Staff: { model: "User", field: "employeeId", prefix: "EMP", filter: { role: { $ne: "customer" } } },
});

const failure = (message, status = 400) => Object.assign(new Error(message), { status });
export const recordNumberStem = (definition, date = new Date()) => `${definition.prefix}-${definition.annual ? `${getRiyadhCreationYear(date)}-` : ""}`;
export const recordCounterKey = (stem) => `record-number:${stem}`;
export const formatRecordNumber = (stem, sequence) => {
  if (!Number.isInteger(sequence) || sequence < 1 || sequence > 999999) throw failure(`Record ID capacity reached for ${stem}`, 503);
  return `${stem}${String(sequence).padStart(6, "0")}`;
};

export async function highestRecordSequence(Model, definition, stem) {
  const row = await Model.findOne({ [definition.field]: new RegExp(`^${stem}\\d{6}$`, "i") }).collation({ locale: "en", strength: 2 }).sort({ [definition.field]: -1 }).select(definition.field).lean();
  return row ? Number(row[definition.field].slice(-6)) : 0;
}

// Deliberately outside the caller's transaction: aborted writes leave gaps, never reusable IDs.
// The unique counter key serializes reservations, including backfills and concurrent creators.
export async function reserveRecordNumber(type, { date = new Date(), Model } = {}) {
  const definition = RECORD_NUMBERS[type];
  if (!definition) throw failure("Unknown record number type");
  const model = Model || mongoose.model(definition.model || type);
  const stem = recordNumberStem(definition, date);
  const floor = await highestRecordSequence(model, definition, stem);
  if (floor >= 999999) throw failure(`Record ID capacity reached for ${stem}`, 503);
  for (let attempt = 0; attempt < 6; attempt += 1) {
    try {
      const counter = await Counter.findOneAndUpdate(
        { _id: recordCounterKey(stem), seq: { $lt: 999999 } },
        [{ $set: { seq: { $add: [{ $max: [{ $ifNull: ["$seq", 0] }, floor] }, 1] } } }],
        { upsert: true, new: true }
      );
      return formatRecordNumber(stem, counter.seq);
    } catch (error) {
      if (error.code !== 11000) throw error;
      const counter = await Counter.findById(recordCounterKey(stem)).lean();
      if (counter?.seq >= 999999) throw failure(`Record ID capacity reached for ${stem}`, 503);
      if (attempt === 5) throw failure("Record ID reservation is busy; retry the request", 503);
    }
  }
}

export const GENERATED_RECORD_FIELDS = [...new Set(Object.values(RECORD_NUMBERS).map((row) => row.field))];
export function rejectClientRecordNumbers(req, _res, next) {
  if (["GET", "HEAD", "OPTIONS"].includes(req.method)) return next();
  // Check recursively, including nested import/form payloads; these names are never input fields.
  const containsId = (value) => value && typeof value === "object" && Object.entries(value).some(([key, child]) => GENERATED_RECORD_FIELDS.includes(key) || containsId(child));
  if (containsId(req.body)) return next(failure("Record IDs are generated by the server and cannot be supplied or changed"));
  next();
}

export function automaticRecordNumber(schema, { type, when = () => true, existingField = false }) {
  const definition = RECORD_NUMBERS[type];
  const field = definition.field;
  if (!existingField) {
    schema.add({ [field]: { type: String, immutable: true, trim: true, uppercase: true, match: new RegExp(`^${definition.prefix}-${definition.annual ? "\\d{4}-" : ""}\\d{6}$`) } });
    schema.index({ [field]: 1 }, { unique: true, partialFilterExpression: { [field]: { $type: "string" } } });
  } else schema.path(field).immutable(true);
  addRecordSearchIndexes(schema, [field]);
  schema.pre("validate", async function () {
    if (this.isNew && when(this) && !this[field]) this[field] = await reserveRecordNumber(type, { Model: this.constructor });
  });
  schema.pre("insertMany", async function (next, rows) {
    try {
      // insertMany does not run document middleware.
      for (let index = 0; index < rows.length; index += 1) {
        const row = rows[index] instanceof mongoose.Document ? rows[index] : { ...rows[index] };
        rows[index] = row;
        if (when(row) && !row[field]) row[field] = await reserveRecordNumber(type, { Model: this });
      }
      next();
    } catch (error) { next(error); }
  });
  for (const operation of ["updateOne", "updateMany", "findOneAndUpdate", "replaceOne", "findOneAndReplace"]) {
    schema.pre(operation, function () {
      const update = this.getUpdate() || {};
      const modifiesId = (value) => value && typeof value === "object" && Object.entries(value).some(([key, child]) => key === field || key.startsWith(`${field}.`) || (key === "$rename" && Object.values(child).includes(field)) || modifiesId(child));
      if (modifiesId(update)) throw failure(`${field} is immutable`);
      if (this.getOptions().upsert || operation.includes("Replace") || operation === "replaceOne") throw failure("Create numbered records with the model creation service, not replacement/upsert");
    });
  }
}
