"use client";
import { useRef, useState } from "react";
import DarkSelect from "../../ui/DarkSelect.jsx";
import { recordRecipeTrial } from "../../../api/recipeInstructionsApi.js";
const criteria = ["taste", "texture", "portionConsistency", "presentation"];
const blankResult = () => ({ tested: false, score: null, notes: "" });
const numberOrNull = value => value === "" ? null : Number(value);
export default function RecipeTrialForm({ recipe, onChanged, onSessionExpired }) {
  const [values, setValues] = useState(() => ({ trialAt: new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Riyadh", dateStyle: "short", timeStyle: "short" }).format(new Date()).replace(" ", "T"), batchValue: "", batchUnit: recipe.category === "Main Recipes" ? "servings" : "g", yieldValue: "", yieldUnit: "g", yieldBasis: "measured", wasteValue: "", preparation: "", cooking: "", deviations: "", reviewerComments: "", safety: "untested", outcome: "needs_changes", ingredients: recipe.ingredients.map((_, index) => ({ index, quantity: "", brand: "" })), ...Object.fromEntries(criteria.map(key => [key, blankResult()])), delivery: [] }));
  const [busy, setBusy] = useState(false), [error, setError] = useState(""); const retry = useRef(null);
  const set = (key, value) => setValues(current => ({ ...current, [key]: value }));
  const submit = async event => {
    event.preventDefault(); if (busy) return; setBusy(true); setError("");
    const payload = { revision: recipe.revision, trialAt: `${values.trialAt}:00+03:00`, batch: { value: Number(values.batchValue), unit: values.batchUnit, basis: "measured" }, usableYield: values.yieldValue === "" ? null : { value: Number(values.yieldValue), unit: values.yieldUnit, basis: values.yieldBasis }, waste: values.wasteValue === "" ? null : { value: Number(values.wasteValue), unit: "g", basis: "measured" }, ingredients: values.ingredients.map(row => ({ ...row, quantity: numberOrNull(row.quantity) })), ...Object.fromEntries(["preparation", "cooking", "deviations", "reviewerComments", "safety", "outcome", ...criteria].map(key => [key, values[key]])), delivery: values.delivery.map(row => ({ minutes: Number(row.minutes), observations: row.observations })) };
    const signature = JSON.stringify(payload); if (retry.current?.signature !== signature) retry.current = { signature, key: crypto.randomUUID() };
    try { await recordRecipeTrial(recipe.code, { ...payload, requestKey: retry.current.key }); onChanged(); }
    catch (err) { if (err.response?.status === 401) onSessionExpired(); setError(err.response?.data?.message || "Trial save failed. Retry the same form to avoid duplicate records."); }
    finally { setBusy(false); }
  };
  return <details className="recipe-card recipe-no-print p-5"><summary className="cursor-pointer font-semibold text-dune-amber">Record kitchen trial · exact revision {recipe.revision}</summary><form className="mt-4 space-y-4" onSubmit={submit}>
    <p className="recipe-warning">TRIAL ONLY — not regular service. Dish guidance: 10 servings; sauces/preparations use their actual batch size. Record measured values; leave untested fields blank. Passing does not approve. Staff identity is recorded from your session.</p>
    <div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Trial date/time · Asia/Riyadh<input className="recipe-input mt-2" type="datetime-local" required value={values.trialAt} onChange={e => set("trialAt", e.target.value)} /></label><label className="text-sm">Actual batch size<input className="recipe-input mt-2" type="number" step="any" min="0.000001" required value={values.batchValue} onChange={e => set("batchValue", e.target.value)} /></label>
      <label className="text-sm">Batch unit<DarkSelect className="recipe-input mt-2" value={values.batchUnit} onChange={e => set("batchUnit", e.target.value)}><option value="servings">Servings</option><option value="g">Grams</option></DarkSelect></label>
      <label className="text-sm">Actual usable yield (blank = untested)<input className="recipe-input mt-2" type="number" step="any" min="0.000001" value={values.yieldValue} onChange={e => set("yieldValue", e.target.value)} /></label>
      <label className="text-sm">Yield unit<DarkSelect className="recipe-input mt-2" value={values.yieldUnit} onChange={e => set("yieldUnit", e.target.value)}><option value="g">Grams</option><option value="servings">Servings</option></DarkSelect></label>
      <label className="text-sm">Yield basis<DarkSelect className="recipe-input mt-2" value={values.yieldBasis} onChange={e => set("yieldBasis", e.target.value)}><option value="measured">Measured</option><option value="estimated">Estimated (not qualifying)</option></DarkSelect></label>
      <label className="text-sm">Measured waste · g (blank = not measured / not applicable)<input className="recipe-input mt-2" type="number" step="any" min="0" value={values.wasteValue} onChange={e => set("wasteValue", e.target.value)} /></label></div>
    <fieldset className="space-y-3"><legend className="mb-3 font-semibold">Actual ingredient quantities · g</legend>{values.ingredients.map((row, index) => <div key={index} className="grid gap-2 sm:grid-cols-2"><label className="text-xs">{recipe.ingredients[index].name} (blank = unmeasured)<input className="recipe-input mt-1" type="number" step="any" min="0.000001" value={row.quantity} onChange={e => set("ingredients", values.ingredients.map((r, i) => i === index ? { ...r, quantity: e.target.value } : r))} /></label><label className="text-xs">Actual supplier brand (optional)<input className="recipe-input mt-1" maxLength={180} value={row.brand} onChange={e => set("ingredients", values.ingredients.map((r, i) => i === index ? { ...r, brand: e.target.value } : r))} /></label></div>)}</fieldset>
    {["preparation", "cooking", "deviations", "reviewerComments"].map(key => <label key={key} className="block text-sm capitalize">{key} observations<textarea className="recipe-input mt-2" maxLength={3000} value={values[key]} onChange={e => set(key, e.target.value)} /></label>)}
    <div className="grid gap-3 sm:grid-cols-2">{criteria.map(key => <fieldset key={key} className="rounded-lg border border-white/10 p-3"><legend className="text-sm capitalize">{key.replace(/([A-Z])/g, " $1")}</legend><label className="flex gap-2 text-xs"><input type="checkbox" checked={values[key].tested} onChange={e => set(key, { ...values[key], tested: e.target.checked, score: e.target.checked ? 1 : null })} />Actually tested</label>{values[key].tested && <label className="mt-2 block text-xs">Score · 1 poor to 5 excellent<input className="recipe-input mt-1" type="number" min="1" max="5" step="0.1" required value={values[key].score} onChange={e => set(key, { ...values[key], score: Number(e.target.value) })} /></label>}<label className="mt-2 block text-xs">Observations<textarea className="recipe-input mt-1" maxLength={3000} value={values[key].notes} onChange={e => set(key, { ...values[key], notes: e.target.value })} /></label></fieldset>)}</div>
    <fieldset><legend className="mb-2 font-semibold">Delivery tests (only intervals actually tested)</legend>{values.delivery.map((row, i) => <div key={i} className="my-2 grid gap-2 sm:grid-cols-2"><label className="text-xs">Minutes after preparation<input className="recipe-input" type="number" min="0" max="1440" required value={row.minutes} onChange={e => set("delivery", values.delivery.map((r, j) => j === i ? { ...r, minutes: e.target.value } : r))} /></label><label className="text-xs">Actual observations<textarea className="recipe-input" required maxLength={3000} value={row.observations} onChange={e => set("delivery", values.delivery.map((r, j) => j === i ? { ...r, observations: e.target.value } : r))} /></label><button type="button" className="recipe-button justify-self-start" onClick={() => set("delivery", values.delivery.filter((_, j) => j !== i))}>Remove test</button></div>)}<button type="button" className="recipe-button" disabled={values.delivery.length >= 10} onClick={() => set("delivery", [...values.delivery, { minutes: "", observations: "" }])}>Add tested interval</button><p className="mt-2 text-xs text-neutral-400">Manual suggests 20/30 minutes. No entries means delivery untested.</p></fieldset>
    <label className="block text-sm">Food-safety checks<DarkSelect className="recipe-input mt-2" value={values.safety} onChange={e => set("safety", e.target.value)}><option value="untested">Untested / incomplete</option><option value="passed">Passed (actually checked)</option><option value="failed">Failed</option></DarkSelect></label>
    <label className="block text-sm">Trial outcome<DarkSelect className="recipe-input mt-2" value={values.outcome} onChange={e => set("outcome", e.target.value)}><option value="needs_changes">Needs changes</option><option value="passed">Passed</option><option value="failed">Failed</option></DarkSelect></label>
    <p className="text-xs text-neutral-400">Actual photo upload unavailable: private storage is not configured. No sample/generated photos are presented.</p>
    {error && <p role="alert" className="text-red-300">{error}</p>}<button className="recipe-button" disabled={busy}>{busy ? "Saving…" : "Save trial record"}</button>
  </form></details>;
}
