"use client";
import { useEffect, useRef, useState } from "react";
import DarkSelect from "../../ui/DarkSelect.jsx";
import { fetchRecipeHistory, fetchRecipeTrials, saveRecipeInstructionDraft, transitionRecipe } from "../../../api/recipeInstructionsApi.js";
import RecipeTrialForm from "./RecipeTrialForm.jsx";
import GuideRehearsalForm from "./GuideRehearsalForm.jsx";
import TrialRecordView from "./TrialRecordView.jsx";
const checks = { ingredientsUnits: "Ingredients, brands, units and weight basis", usableYield: "Measured usable yield", preparation: "Preparation", assembly: "Assembly / applicable preparation use", servingDelivery: "Serving / tested delivery scope", allergens: "Supplier allergens and shared contact", storage: "Storage / cooling / label guidance", linkedPreparations: "Approved published preparation revisions", qualifiedLocalSafetyReview: "Qualified/local food-safety review completed (not certification)" };
const date = value => value ? new Intl.DateTimeFormat("en-GB", { timeZone: "Asia/Riyadh", dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "Not recorded";
const display = value => value == null ? "Not recorded" : typeof value === "string" ? value : JSON.stringify(value, null, 2);
export default function RecipeWorkflow({ recipe, workingRecipe, manager, view, onSaved, onChanged, onNavigate, onSessionExpired }) {
  const [history, setHistory] = useState(null), [trials, setTrials] = useState(null), [error, setError] = useState("");
  const [reason, setReason] = useState(""), [trialId, setTrialId] = useState(""), [checklist, setChecklist] = useState({}), [busy, setBusy] = useState(false);
  const retry = useRef(null), mounted = useRef(true);
  useEffect(() => {
    mounted.current = true; const controller = new AbortController();
    const options = { signal: controller.signal, params: { view, revision: recipe.revision } };
    Promise.all([fetchRecipeHistory(recipe.code, options), fetchRecipeTrials(recipe.code, options)]).then(([h, t]) => { if (!controller.signal.aborted) { setHistory(h); setTrials(t); } }).catch(err => { if (!controller.signal.aborted) { if (err.response?.status === 401) onSessionExpired(); setError(err.response?.data?.message || "History/trials unavailable. Reload before review."); } });
    return () => { mounted.current = false; controller.abort(); };
  }, [recipe.code, recipe.revision, recipe.workflowVersion, view, onSessionExpired]);
  const act = async (action, restoreRevision) => {
    if (busy) return; setBusy(true); setError("");
    const payload = restoreRevision ? { revision: workingRecipe.revision, workflowVersion: workingRecipe.workflowVersion || 0, status: "draft", reviewNotes: workingRecipe.reviewNotes || "", inventoryRecipe: workingRecipe.inventoryRecipe, restoreRevision, reason } : { revision: recipe.revision, workflowVersion: recipe.workflowVersion || 0, reason, ...(action === "approve" ? { trialId, checklist } : {}) };
    const signature = JSON.stringify({ action, payload }); if (retry.current?.signature !== signature) retry.current = { signature, key: crypto.randomUUID() };
    try { const result = restoreRevision ? await saveRecipeInstructionDraft(recipe.code, { ...payload, requestKey: retry.current.key }) : await transitionRecipe(recipe.code, action, { ...payload, requestKey: retry.current.key }); if (mounted.current) onSaved(result); }
    catch (err) { if (mounted.current) { if (err.response?.status === 401) onSessionExpired(); setError(err.response?.data?.message || "Workflow action failed. Reload/retry the same request safely."); } }
    finally { if (mounted.current) setBusy(false); }
  };
  const working = workingRecipe?.revision === recipe.revision;
  const more = async kind => {
    const state = kind === "history" ? history : trials;
    try { const next = await (kind === "history" ? fetchRecipeHistory : fetchRecipeTrials)(recipe.code, { params: { view, revision: recipe.revision, before: state.nextBefore } }); if (mounted.current) (kind === "history" ? setHistory : setTrials)({ rows: [...state.rows, ...next.rows], nextBefore: next.nextBefore }); }
    catch { if (mounted.current) setError("More records unavailable. Retry loading."); }
  };
  return <section className="space-y-4">
    {recipe.approval && <div className="recipe-card p-4 text-sm">Approved r{recipe.revision} by {recipe.approval.actor.name} · {date(recipe.approval.at)} (Asia/Riyadh). Internal operational review only.<p className="mt-2 break-all text-xs">Qualifying trial: {recipe.qualifyingTrialId} · {recipe.approval.reason}</p>{recipe.publication && <p className="mt-2">Published by {recipe.publication.actor.name} · {date(recipe.publication.at)}{recipe.currentPublished ? " · Current service version" : " · Historical service version"}</p>}</div>}
    {recipe.dependencyPins?.length > 0 && <section className="recipe-card p-4"><h3 className="font-semibold">Pinned preparation instructions</h3>{recipe.dependencyPins.map(pin => <div key={pin.code} className="mt-3 text-sm"><button className="recipe-button recipe-no-print" onClick={() => onNavigate(pin.code, pin.revision)}>{pin.code} · revision {pin.revision}</button><span className="recipe-print-only">{pin.code} · revision {pin.revision}</span>{pin.updateAvailable && <p className="mt-2 text-dune-amber">Update available — review required. This dish still uses the pinned version; create a new dish revision to adopt it.</p>}</div>)}</section>}
    <div className="recipe-no-print space-y-4">
      {working && recipe.status === "trial_required" && (recipe.category === "Kitchen Guides" ? <GuideRehearsalForm recipe={recipe} onChanged={onChanged} onSessionExpired={onSessionExpired} /> : <RecipeTrialForm key={`${recipe.code}-${recipe.revision}`} recipe={recipe} onChanged={onChanged} onSessionExpired={onSessionExpired} />)}
      <details className="recipe-card p-5"><summary className="cursor-pointer font-semibold">Trial records · r{recipe.revision}</summary>{!trials && !error && <p role="status">Loading trials…</p>}{trials?.rows.length === 0 && <p className="mt-3 text-sm text-neutral-400">No recorded trial. Untested — not evidence of approval.</p>}{trials?.rows.map(trial => <details key={trial.id} className="mt-3 rounded-lg border border-white/10 p-3"><summary className="cursor-pointer text-sm">{trial.record.outcome.replaceAll("_", " ")} · {trial.actor.name} · {date(trial.record.trialAt)}</summary><TrialRecordView record={trial.record} /></details>)}{trials?.nextBefore && <button className="recipe-button mt-3" onClick={() => more("trials")}>Load older trials</button>}</details>
      {manager && <details className="recipe-card p-5"><summary className="cursor-pointer font-semibold text-dune-amber">Authorized review / version actions</summary><div className="mt-4 space-y-3"><p className="text-xs text-neutral-400">Approval is an internal review, not legal certification. The backend verifies the exact trial/revision, required checks and published dependencies.</p><label className="block text-sm">Action reason / reviewer comments<textarea className="recipe-input mt-2" maxLength={3000} value={reason} onChange={e => setReason(e.target.value)} /></label>
        {working && recipe.status === "draft" && <button className="recipe-button" disabled={busy || !reason.trim()} onClick={() => act("submit")}>Request kitchen trial</button>}
        {working && recipe.status === "trial_required" && <><label className="block text-sm">Qualifying passed trial<DarkSelect className="recipe-input mt-2" value={trialId} onChange={e => setTrialId(e.target.value)}><option value="">Select a trial</option>{trials?.rows.filter(t => t.record.outcome === "passed").map(t => <option key={t.id} value={t.id}>{t.actor.name} · {date(t.record.trialAt)}</option>)}</DarkSelect></label><fieldset className="space-y-2"><legend className="mb-2 text-sm font-semibold">Review checklist</legend>{Object.entries(checks).map(([key, label]) => <label key={key} className="flex items-start gap-2 text-xs"><input type="checkbox" checked={Boolean(checklist[key])} onChange={e => setChecklist(c => ({ ...c, [key]: e.target.checked }))} />{recipe.category === "Kitchen Guides" && ["ingredientsUnits", "usableYield", "assembly", "servingDelivery"].includes(key) ? `${label} — applicability checked; no production quantities invented` : label}</label>)}</fieldset><button className="recipe-button" disabled={busy || !reason.trim() || !trialId || !Object.keys(checks).every(key => checklist[key])} onClick={() => act("approve")}>Record authorized approval</button></>}
        {working && recipe.status === "approved" && <button className="recipe-button" disabled={busy || !reason.trim()} onClick={() => act("publish")}>Publish for regular service</button>}
      </div></details>}
      <details className="recipe-card p-5"><summary className="cursor-pointer font-semibold">Version history / differences</summary>{!history && !error && <p role="status">Loading history…</p>}{history?.rows.map(row => <details key={row.revision} className="mt-3 rounded-lg border border-white/10 p-3"><summary className="cursor-pointer text-sm">r{row.revision} · {row.status.replaceAll("_", " ")}{row.currentPublished ? " · Current published" : ""} · {date(row.createdAt)}</summary><p className="mt-2 text-xs">{row.actor?.name || "Legacy draft"} · {row.reason}{row.restoredFrom && ` · Restored from r${row.restoredFrom}`}</p><div className="my-3 flex flex-wrap gap-2"><button className="recipe-button" onClick={() => onNavigate(recipe.code, row.revision)}>Read exact revision</button>{manager && workingRecipe && <button className="recipe-button" disabled={busy || !reason.trim()} onClick={() => act("restore", row.revision)}>Restore as NEW draft (reason above)</button>}</div>{row.changes?.map(change => <details key={change.field} className="my-2"><summary className="cursor-pointer text-xs text-dune-amber">Changed: {change.field}</summary><div className="grid gap-2 sm:grid-cols-2"><div><p className="text-xs">Previous</p><pre className="recipe-diff">{display(change.before)}</pre></div><div><p className="text-xs">New</p><pre className="recipe-diff">{display(change.after)}</pre></div></div></details>)}</details>)}{history?.nextBefore && <button className="recipe-button mt-3" onClick={() => more("history")}>Load older revisions</button>}</details>
      {error && <p role="alert" className="recipe-warning">{error}<button className="recipe-button ml-2" onClick={onChanged}>Reload workflow</button></p>}
    </div>
  </section>;
}
