import express from "express";
import { rejectClientRecordNumbers } from "../services/recordNumberService.js";
import { createPosSale, listPosSales } from "../controllers/posController.js";
import { protect, requireCapability } from "../middleware/auth.js";
import { CAPABILITIES } from "../config/permissions.js";
import { closeShift, currentShift, getShift, getShiftConfig, listShifts, openShift, postCashMovement, reopenShift } from "../controllers/posShiftController.js";
import { createHeldSale, updateHeldSale, listHeldSales, getHeldSale, cancelHeldSale } from "../controllers/posHeldSaleController.js";
import { requestPosDiscountApproval } from "../controllers/posDiscountController.js";
import { rateLimit } from "../middleware/security.js";
import { resolvePosSession } from "../services/posSessionService.js";
import { listTerminals, writeTerminal, posSession, lockSession, unlockSession, listCashiers, writePin, listQuickMenu, writeQuickItem } from "../controllers/posOperationsController.js";
import { getPosSale, reprintPosSale, voidSale, requestPosRefund, repeatPosSale } from "../controllers/posSaleHistoryController.js";
import { changeRefundStatus } from "../controllers/refundController.js";

const router = express.Router();
router.use(rejectClientRecordNumbers);
router.use(protect, resolvePosSession, requireCapability(CAPABILITIES.POS_OPERATE));
router.get("/session", posSession);
router.post("/session/lock", lockSession);
router.post("/session/unlock", rateLimit({ windowMs: 5 * 60_000, max: 10, keyPrefix: "pos-unlock" }), unlockSession());
router.post("/session/switch", rateLimit({ windowMs: 5 * 60_000, max: 10, keyPrefix: "pos-switch" }), unlockSession(true));
router.get("/session/cashiers", listCashiers);
router.put("/session/pins/:id", requireCapability(CAPABILITIES.STAFF_MANAGE), writePin);
router.get("/terminals", listTerminals);
router.post("/terminals", requireCapability(CAPABILITIES.POS_TERMINAL_MANAGE), writeTerminal);
router.patch("/terminals/:id", requireCapability(CAPABILITIES.POS_TERMINAL_MANAGE), writeTerminal);
router.get("/quick-menu", listQuickMenu);
router.put("/quick-menu", requireCapability(CAPABILITIES.POS_QUICK_MENU_MANAGE), writeQuickItem);
router.route("/sales").get(listPosSales).post(createPosSale);
router.get("/sales/:id", getPosSale);
router.post("/sales/:id/reprint", reprintPosSale);
router.post("/sales/:id/repeat", repeatPosSale);
router.post("/sales/:id/void", requireCapability(CAPABILITIES.POS_VOID), rateLimit({ windowMs: 60_000, max: 20, keyPrefix: "pos-void" }), voidSale);
router.post("/sales/:id/refunds", requireCapability(CAPABILITIES.POS_REFUND), rateLimit({ windowMs: 60_000, max: 20, keyPrefix: "pos-refund" }), requestPosRefund);
for (const action of ["approve", "complete", "reject", "cancel"]) router.post(`/refunds/:refundId/${action}`, requireCapability(CAPABILITIES.POS_REFUND), rateLimit({ windowMs: 60_000, max: 30, keyPrefix: "pos-refund-action" }), changeRefundStatus(action));
router.route("/held-sales").get(listHeldSales).post(createHeldSale);
router.route("/held-sales/:id").get(getHeldSale).patch(updateHeldSale).delete(cancelHeldSale);
router.post("/discount-approvals", rateLimit({ windowMs: 5 * 60_000, max: 10, keyPrefix: "pos-discount-approval" }), requestPosDiscountApproval);
router.get("/shift-config", getShiftConfig);
router.get("/shifts/current", currentShift);
router.post("/shifts/open", openShift);
router.post("/shifts/:shiftId/cash-movements", rateLimit({ windowMs: 60_000, max: 30, keyPrefix: "pos-cash" }), postCashMovement);
router.post("/shifts/:shiftId/close", rateLimit({ windowMs: 60_000, max: 20, keyPrefix: "pos-close" }), closeShift);
router.get("/shifts", requireCapability(CAPABILITIES.POS_SHIFT_MANAGE), listShifts);
router.get("/shifts/:shiftId", getShift);
router.post("/shifts/:shiftId/reopen", requireCapability(CAPABILITIES.POS_SHIFT_MANAGE), reopenShift);

export default router;
