"use client";

import DarkSelect from "@/src/components/ui/DarkSelect.jsx";

import { useEffect, useState } from "react";
import { ClipboardCheck, LoaderCircle, Play, Plus, RefreshCw, XCircle } from "lucide-react";
import { toast } from "sonner";
import { cancelInventoryCount, completeInventoryCount, createInventoryCount, fetchInventoryCategories, fetchInventoryCounts, reviewInventoryCount, submitInventoryCount } from "@/src/api/inventoryApi.js";
import { useAuth } from "@/src/context/AuthContext.jsx";
import { Badge, Button, DataTable, EmptyState, Field, LoadingState, Modal, PageHeader, cardClass, inputClass, textareaClass } from "./InventoryUI.jsx";
import { apiErrorMessage, formatDate, formatQuantity, humanize } from "./inventoryUtils.js";
import useInventoryResource from "./useInventoryResource.js";

const tones = { draft: "info", in_progress: "warning", review_required: "danger", completed: "success", cancelled: "danger" };

function CountSheet({ count, onComplete, submitting, canApprove }) {
  const [lines, setLines] = useState(() => Object.fromEntries(count.items.map((line) => [line._id, { countedQuantity: count.blindCount ? "" : line.expectedQuantity, notes: "" }])));
  const set = (id, field, value) => setLines((current) => ({ ...current, [id]: { ...current[id], [field]: value } }));
  return <form onSubmit={(event) => { event.preventDefault(); onComplete(count._id, count.items.map((line) => ({ lineId: line._id, countedQuantity: Number(lines[line._id].countedQuantity), notes: lines[line._id].notes }))); }} className="space-y-4"><div className="rounded-xl border border-amber-500/20 bg-amber-500/5 p-4 text-xs leading-5 text-amber-100/70">{count.blindCount ? "Blind count is enabled. Expected stock and variance stay hidden while you enter physical quantities." : "Enter the physically counted quantity for every line. Differences create audited inventory-count adjustment transactions."}</div><div className="max-h-[55vh] space-y-2 overflow-y-auto pr-1">{count.items.map((line) => { const counted = Number(lines[line._id].countedQuantity); const variance = counted - line.expectedQuantity; return <div key={line._id} className="grid items-end gap-3 rounded-xl border border-white/10 bg-black/20 p-3 sm:grid-cols-[1fr_0.7fr_0.7fr_0.8fr]"><div><p className="text-sm font-medium text-white">{line.itemName}</p><p className="text-[0.65rem] text-neutral-600">{line.sku}</p></div><div><p className="text-[0.68rem] text-neutral-600">Expected</p><p className="mt-2 text-sm text-neutral-300">{count.blindCount ? "Hidden" : formatQuantity(line.expectedQuantity)}</p></div><Field label="Counted"><input required min="0" step="any" type="number" className={inputClass} value={lines[line._id].countedQuantity} onChange={(event) => set(line._id, "countedQuantity", event.target.value)} /></Field><div><p className="text-[0.68rem] text-neutral-600">Variance</p><p className={`mt-2 text-sm font-semibold ${variance === 0 ? "text-neutral-400" : variance > 0 ? "text-emerald-400" : "text-red-400"}`}>{count.blindCount ? "Hidden" : <>{variance > 0 ? "+" : ""}{Number.isFinite(variance) ? variance : 0}</>}</p></div></div>; })}</div><div className="flex justify-end"><Button type="submit" disabled={submitting}>{submitting ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <ClipboardCheck className="h-4 w-4" />}{canApprove ? "Complete count & adjust stock" : "Submit for approval"}</Button></div></form>;
}

export default function InventoryCountPage() {
  const { user } = useAuth();
  const canApprove = ["admin", "manager"].includes(user?.role);
  const { data = [], loading, reload } = useInventoryResource(fetchInventoryCounts, []);
  const [categories, setCategories] = useState([]); const [createOpen, setCreateOpen] = useState(false);
  const [activeCount, setActiveCount] = useState(null); const [submitting, setSubmitting] = useState(false);
  const [form, setForm] = useState({ category: "", notes: "", blindCount: false });
  useEffect(() => { fetchInventoryCategories().then(setCategories).catch(() => undefined); if (typeof window !== "undefined" && new URLSearchParams(window.location.search).get("action") === "add") setCreateOpen(true); }, []);
  const create = async (event) => { event.preventDefault(); setSubmitting(true); try { const row = await createInventoryCount({ category: form.category || undefined, notes: form.notes, blindCount: form.blindCount }); toast.success(`${row.countNumber} started.`); setCreateOpen(false); setForm({ category: "", notes: "", blindCount: false }); setActiveCount(row); reload({ silent: true }); } catch (error) { toast.error(apiErrorMessage(error, "Unable to start inventory count.")); } finally { setSubmitting(false); } };
  const complete = async (id, items) => { setSubmitting(true); try { if (canApprove) { await completeInventoryCount(id, items); toast.success("Inventory count completed and variances recorded."); } else { await submitInventoryCount(id, items); toast.success("Inventory count submitted for manager approval."); } setActiveCount(null); reload({ silent: true }); } catch (error) { if (error.response?.status === 409) { setActiveCount(null); reload({ silent: true }); } toast.error(apiErrorMessage(error, "Unable to complete inventory count.")); } finally { setSubmitting(false); } };
  const review = async (row) => { if (!window.confirm(`Resnapshot ${row.countNumber} and request a recount?`)) return; try { const updated = await reviewInventoryCount(row._id); toast.success("Conflict cleared. Recount using the latest stock snapshot."); setActiveCount(updated); reload({ silent: true }); } catch (error) { toast.error(apiErrorMessage(error, "Unable to review this count.")); } };
  const approve = async (row) => { setSubmitting(true); try { await completeInventoryCount(row._id, []); toast.success("Inventory count approved and adjustments recorded."); reload({ silent: true }); } catch (error) { toast.error(apiErrorMessage(error, "Unable to approve this count.")); reload({ silent: true }); } finally { setSubmitting(false); } };
  const cancel = async (row) => { if (!window.confirm(`Cancel ${row.countNumber}?`)) return; try { await cancelInventoryCount(row._id); toast.success("Inventory count cancelled."); reload({ silent: true }); } catch (error) { toast.error(apiErrorMessage(error)); } };
  const columns = [
    { key: "number", label: "Count number", render: (row) => <span className="font-semibold text-white">{row.countNumber}</span> },
    { key: "status", label: "Status", render: (row) => <Badge tone={tones[row.status]}>{humanize(row.status)}</Badge> },
    { key: "items", label: "Items", render: (row) => row.items.length },
    { key: "created", label: "Created", render: (row) => formatDate(row.createdAt, true) },
    { key: "createdBy", label: "Created by", render: (row) => row.createdBy?.name || "—" },
    { key: "completed", label: "Completed", render: (row) => formatDate(row.completedAt, true) },
    { key: "actions", label: "", render: (row) => row.status === "in_progress" ? <div className="flex justify-end gap-1"><button type="button" onClick={() => setActiveCount(row)} className="rounded-lg p-2 text-neutral-500 hover:bg-emerald-500/10 hover:text-emerald-300" aria-label="Continue count"><Play className="h-4 w-4" /></button>{canApprove && <button type="button" onClick={() => cancel(row)} className="rounded-lg p-2 text-neutral-500 hover:bg-red-500/10 hover:text-red-300" aria-label="Cancel count"><XCircle className="h-4 w-4" /></button>}</div> : row.status === "review_required" && canApprove ? <div className="flex justify-end gap-1">{row.items.some((line) => line.conflict) ? <button type="button" onClick={() => review(row)} className="flex items-center gap-1 rounded-lg px-2 py-1.5 text-xs text-red-300 hover:bg-red-500/10"><RefreshCw className="h-3.5 w-3.5" />Review &amp; recount</button> : <button type="button" onClick={() => approve(row)} disabled={submitting} className="flex items-center gap-1 rounded-lg px-2 py-1.5 text-xs text-emerald-300 hover:bg-emerald-500/10"><ClipboardCheck className="h-3.5 w-3.5" />Approve</button>}</div> : null },
  ];
  return <div className="mx-auto max-w-[1500px]"><PageHeader title="Inventory Count" description="Run physical stock counts and convert every variance into an auditable adjustment." actions={<Button onClick={() => setCreateOpen(true)}><Plus className="h-4 w-4" />Start inventory count</Button>} /><section className={cardClass}>{loading ? <LoadingState /> : <DataTable columns={columns} rows={data} empty={<EmptyState title="No inventory counts yet" description="Start a full or category-based count." />} />}</section><Modal open={createOpen} onClose={() => setCreateOpen(false)} title="Start inventory count"><form onSubmit={create} className="space-y-4"><Field label="Scope"><DarkSelect className={inputClass} value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}><option value="">All active inventory items</option>{categories.map((row) => <option key={row._id} value={row._id}>{row.name}</option>)}</DarkSelect></Field><label className="flex items-center gap-3 rounded-xl border border-white/10 bg-black/20 p-3 text-sm text-neutral-300"><input type="checkbox" checked={form.blindCount} onChange={(event) => setForm({ ...form, blindCount: event.target.checked })} className="h-4 w-4 accent-orange-500" /><span><span className="block text-white">Blind count</span><span className="text-xs text-neutral-500">Hide expected stock and variance while counting.</span></span></label><Field label="Count notes"><textarea className={textareaClass} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></Field><div className="flex justify-end"><Button type="submit" disabled={submitting}>{submitting ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Start count</Button></div></form></Modal><Modal open={Boolean(activeCount)} onClose={() => setActiveCount(null)} title={activeCount ? `Count sheet · ${activeCount.countNumber}` : "Count sheet"} maxWidth="max-w-5xl">{activeCount && <CountSheet count={activeCount} onComplete={complete} submitting={submitting} canApprove={canApprove} />}</Modal></div>;
}
