"use client";

import { useEffect, useState } from "react";
import { Database, LoaderCircle, Save, Sheet } from "lucide-react";
import { toast } from "sonner";
import { fetchInventorySettings, updateInventorySettings } from "@/src/api/inventoryApi.js";
import { Badge, Button, Field, LoadingState, PageHeader, cardClass, inputClass } from "./InventoryUI.jsx";
import { apiErrorMessage, formatDate } from "./inventoryUtils.js";
import useInventoryResource from "./useInventoryResource.js";

export default function InventorySettingsPage() {
  const { data, loading, reload } = useInventoryResource(fetchInventorySettings, []);
  const [form, setForm] = useState({ outletName: "", expiryAlertDays: 7, defaultAllowNegativeStock: false }); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { if (data) setForm({ outletName: data.outletName, expiryAlertDays: data.expiryAlertDays, defaultAllowNegativeStock: data.defaultAllowNegativeStock }); }, [data]);
  const save = async (event) => { event.preventDefault(); setSubmitting(true); try { await updateInventorySettings({ ...form, expiryAlertDays: Number(form.expiryAlertDays) }); toast.success("Inventory settings saved."); reload({ silent: true }); } catch (error) { toast.error(apiErrorMessage(error, "Unable to save settings.")); } finally { setSubmitting(false); } };
  return <div className="mx-auto max-w-5xl"><PageHeader title="Inventory Settings" description="Control outlet defaults and alert behavior without changing the wider restaurant application." />{loading ? <div className={cardClass}><LoadingState /></div> : <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]"><form onSubmit={save} className={`${cardClass} p-5 sm:p-6`}><h2 className="font-body text-base font-semibold text-white">Operational settings</h2><div className="mt-5 space-y-5"><Field label="Outlet name"><input required className={inputClass} value={form.outletName} onChange={(event) => setForm({ ...form, outletName: event.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Currency"><input disabled className={`${inputClass} cursor-not-allowed text-neutral-500`} value="SAR" readOnly /></Field><Field label="Expiry alert window (days)"><input required min="1" max="365" type="number" className={inputClass} value={form.expiryAlertDays} onChange={(event) => setForm({ ...form, expiryAlertDays: event.target.value })} /></Field></div><label className="flex items-start gap-3 rounded-xl border border-white/10 bg-black/20 p-4 text-xs text-neutral-400"><input type="checkbox" checked={form.defaultAllowNegativeStock} onChange={(event) => setForm({ ...form, defaultAllowNegativeStock: event.target.checked })} className="mt-0.5 h-4 w-4 accent-amber-500" /><span><strong className="block text-neutral-200">Allow negative stock by default</strong>Individual movement requests still require explicit authorization. Keep disabled for normal operation.</span></label><div className="flex justify-end"><Button type="submit" disabled={submitting}>{submitting ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}Save settings</Button></div></div></form><div className="space-y-4"><article className={`${cardClass} p-5`}><div className="flex items-center justify-between"><span className="rounded-xl bg-emerald-500/10 p-2.5 text-emerald-400"><Database className="h-5 w-5" /></span><Badge tone="success">Source of truth</Badge></div><h2 className="mt-4 font-body text-base font-semibold text-white">MongoDB inventory</h2><p className="mt-2 text-xs leading-5 text-neutral-500">Website inventory, stock history and purchase records remain authoritative.</p></article><article className={`${cardClass} p-5`}><div className="flex items-center justify-between"><span className="rounded-xl bg-white/5 p-2.5 text-neutral-400"><Sheet className="h-5 w-5" /></span><Badge>Not connected</Badge></div><h2 className="mt-4 font-body text-base font-semibold text-white">Google Sheets sync</h2><p className="mt-2 text-xs leading-5 text-neutral-500">No connection is active. Stable IDs, predictable fields, timestamps and the service layer are ready for a later sync adapter.</p><p className="mt-3 text-[0.65rem] text-neutral-700">Last sync: {formatDate(data?.googleSheetsSync?.lastSyncedAt, true)}</p></article></div></div>}</div>;
}
