"use client";

import { useEffect, useState } from "react";
import { ArrowDownRight, ArrowUpRight, Minus } from "lucide-react";
import DarkSelect from "@/src/components/ui/DarkSelect.jsx";
import { fetchInventoryItems, fetchPurchasePriceHistory, fetchSuppliers } from "@/src/api/inventoryApi.js";
import { Badge, DataTable, EmptyState, LoadingState, Money, PageHeader, StatCard, cardClass, inputClass } from "./InventoryUI.jsx";
import { formatDate, humanize } from "./inventoryUtils.js";
import useInventoryResource from "./useInventoryResource.js";

export default function PurchasePriceHistoryPage() {
  const [item, setItem] = useState(""); const [supplier, setSupplier] = useState(""); const [options, setOptions] = useState({ items: [], suppliers: [] });
  useEffect(() => { Promise.all([fetchInventoryItems({ limit: 100, sortBy: "name", sortOrder: "asc" }), fetchSuppliers()]).then(([items, suppliers]) => setOptions({ items: items.data, suppliers })); }, []);
  const { data, loading } = useInventoryResource(() => fetchPurchasePriceHistory({ item: item || undefined, supplier: supplier || undefined, limit: 300 }), [item, supplier]);
  const summary = data?.summaries?.[0]; const ChangeIcon = Number(summary?.change || 0) > 0 ? ArrowUpRight : Number(summary?.change || 0) < 0 ? ArrowDownRight : Minus;
  const columns = [{ key: "date", label: "Effective", render: (row) => formatDate(row.effectiveAt, true) }, { key: "item", label: "Item", render: (row) => <div><p className="font-medium text-white">{row.item?.name}</p><p className="text-[0.65rem] text-neutral-600">{row.sku}</p></div> }, { key: "supplier", label: "Supplier", render: (row) => row.supplier?.name || "—" }, { key: "source", label: "Price source", render: (row) => <Badge tone={row.priceType === "invoiced" ? "success" : row.priceType === "proposed" ? "info" : "warning"}>{humanize(row.priceType)}</Badge> }, { key: "unit", label: "Purchase price", render: (row) => <span><Money value={row.unitPrice} /> / {row.unit}</span> }, { key: "base", label: "Normalized base price", render: (row) => <Money value={row.baseUnitPrice} /> }, { key: "reference", label: "Reference", render: (row) => row.invoice ? "Supplier invoice" : row.receipt ? "Receipt" : "Purchase order" }];
  return <div className="mx-auto max-w-[1600px]"><PageHeader title="Purchase Price History" description="Append-only proposed, approved, received and posted-invoice prices normalized to each item's base unit." />{summary && <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Last purchase price" value={<Money value={summary.lastPrice} />} caption={humanize(summary.source)} /><StatCard label="Previous price" value={summary.previousPrice == null ? "—" : <Money value={summary.previousPrice} />} /><StatCard label="Price variance" value={<span className="flex items-center gap-1"><ChangeIcon className="h-5 w-5" />{summary.changePercent == null ? "—" : `${summary.changePercent}%`}</span>} tone={summary.change > 0 ? "red" : "green"} /><StatCard label="Average actual / fallback" value={<Money value={summary.averagePrice} />} /></div>}<section className={cardClass}><div className="flex flex-wrap gap-3 border-b border-white/10 p-4"><DarkSelect className={`${inputClass} w-64`} value={item} onChange={(event) => setItem(event.target.value)}><option value="">All inventory items</option>{options.items.map((row) => <option key={row._id} value={row._id}>{row.name} · {row.sku}</option>)}</DarkSelect><DarkSelect className={`${inputClass} w-64`} value={supplier} onChange={(event) => setSupplier(event.target.value)}><option value="">All suppliers</option>{options.suppliers.map((row) => <option key={row._id} value={row._id}>{row.name}</option>)}</DarkSelect></div>{loading ? <LoadingState /> : <DataTable rows={data?.rows} columns={columns} empty={<EmptyState title="No purchase price history" description="Prices appear as purchase orders move through approval, receipt and invoice posting." />} />}</section></div>;
}
