"use client";

import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Calculator, CircleDollarSign, FilePlus2, RefreshCw, Settings2, TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import DarkSelect from "@/src/components/ui/DarkSelect.jsx";
import { useAuth } from "@/src/context/AuthContext.jsx";
import { dismissReorderSuggestion, fetchReorderSuggestions, fetchSuppliers, generateReorderDrafts, recalculateReorderSuggestions, reviewReorderSuggestion } from "@/src/api/inventoryApi.js";
import { Badge, Button, DataTable, EmptyState, Field, LoadingState, Modal, Money, PageHeader, Pagination, StatCard, cardClass, inputClass, textareaClass } from "./InventoryUI.jsx";
import { apiErrorMessage, formatDate, formatQuantity, humanize } from "./inventoryUtils.js";

const tone = { critical: "danger", high: "warning", medium: "info", low: "neutral" };

export default function ReorderSuggestionsPage() {
  const { user } = useAuth(); const canManage = ["admin", "manager", "inventory", "storekeeper"].includes(user?.role); const canGenerate = ["admin", "manager"].includes(user?.role);
  const [data, setData] = useState(null); const [suppliers, setSuppliers] = useState([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [page, setPage] = useState(1); const [status, setStatus] = useState(""); const [severity, setSeverity] = useState(""); const [search, setSearch] = useState(""); const [selected, setSelected] = useState([]); const [details, setDetails] = useState(null); const [review, setReview] = useState(null); const [reviewForm, setReviewForm] = useState({ quantity: "", supplier: "", unitPrice: "", reason: "" });
  const load = useCallback(async () => { setLoading(true); try { const [response, supplierRows] = await Promise.all([fetchReorderSuggestions({ page, status, severity, search }), fetchSuppliers()]); setData(response); setSuppliers(supplierRows); } catch (error) { toast.error(apiErrorMessage(error, "Unable to load reorder suggestions.")); } finally { setLoading(false); } }, [page, search, severity, status]);
  useEffect(() => { load(); }, [load]);
  const recalculate = async () => { setBusy(true); try { await recalculateReorderSuggestions(); await load(); toast.success("Reorder suggestions recalculated."); } catch (error) { toast.error(apiErrorMessage(error, "Recalculation failed.")); } finally { setBusy(false); } };
  const openReview = (row) => { setReview(row); setReviewForm({ quantity: row.reviewedQuantity ?? row.suggestedQuantity, supplier: row.reviewedSupplier?._id || row.supplier?._id || "", unitPrice: row.reviewedUnitPrice ?? "", reason: "" }); };
  const saveReview = async (event) => { event.preventDefault(); setBusy(true); try { await reviewReorderSuggestion(review._id, { ...reviewForm, quantity: Number(reviewForm.quantity) }); setReview(null); await load(); toast.success("Suggestion reviewed."); } catch (error) { toast.error(apiErrorMessage(error, "Unable to review suggestion.")); } finally { setBusy(false); } };
  const dismiss = async (row) => { const reason = window.prompt("Reason for snoozing this suggestion"); if (!reason) return; try { await dismissReorderSuggestion(row._id, { reason, days: 7 }); await load(); toast.success("Suggestion snoozed for 7 days."); } catch (error) { toast.error(apiErrorMessage(error)); } };
  const generate = async () => { if (!selected.length) return; setBusy(true); try { const result = await generateReorderDrafts({ suggestionIds: selected, idempotencyKey: crypto.randomUUID() }); setSelected([]); await load(); toast.success(`${result.purchaseOrders.length} draft purchase order(s) created.`); } catch (error) { toast.error(apiErrorMessage(error, "Draft generation failed.")); } finally { setBusy(false); } };
  const columns = [
    { key: "select", label: "", render: (row) => <input type="checkbox" aria-label={`Select ${row.item?.name}`} disabled={!canGenerate || !["open", "reviewed"].includes(row.status)} checked={selected.includes(row._id)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, row._id] : current.filter((id) => id !== row._id))} /> },
    { key: "item", label: "Item", render: (row) => <button type="button" onClick={() => setDetails(row)} className="text-left"><span className="block font-medium text-white">{row.item?.name}</span><span className="text-[0.65rem] text-neutral-600">{row.item?.sku}</span></button> },
    { key: "stock", label: "Usable / projected", render: (row) => `${formatQuantity(row.breakdown?.usableOnHand, row.breakdown?.baseUnit)} / ${formatQuantity(row.breakdown?.projectedAvailable, row.breakdown?.baseUnit)}` },
    { key: "policy", label: "Reorder / target", render: (row) => `${row.breakdown?.effectiveReorderPoint} / ${row.breakdown?.effectiveTarget} ${row.breakdown?.baseUnit}` },
    { key: "quantity", label: "Suggested", render: (row) => <span className="font-semibold text-dune-amber">{row.reviewedQuantity ?? row.suggestedQuantity} {row.breakdown?.purchaseUnit}</span> },
    { key: "supplier", label: "Supplier", render: (row) => row.reviewedSupplier?.name || row.supplier?.name || <Badge tone="danger">Missing</Badge> },
    { key: "price", label: "Price / value", render: (row) => <div><Money value={row.suggestedUnitPrice} /><p className="text-[0.62rem] text-neutral-600">{humanize(row.priceSource)} · {row.estimatedTotal == null ? "Review required" : `Total ${row.estimatedTotal.toFixed(2)}`}</p></div> },
    { key: "status", label: "Status", render: (row) => <div className="space-y-1"><Badge tone={tone[row.severity]}>{humanize(row.severity)}</Badge><p className="text-[0.62rem] text-neutral-600">{humanize(row.status)}</p></div> },
    { key: "actions", label: "Actions", render: (row) => canManage && <div className="flex gap-1"><Button size="sm" variant="secondary" onClick={() => openReview(row)}>Review</Button><Button size="sm" variant="ghost" onClick={() => dismiss(row)}>Snooze</Button></div> },
  ];
  const summary = data?.summary || {};
  return <div className="mx-auto max-w-[1680px]"><PageHeader title="Reorder Suggestions" description="Explainable, demand-aware purchase recommendations. Quantities shown here are purchase units; stock calculations use base units." actions={<><Button variant="secondary" onClick={recalculate} disabled={!canManage || busy}><RefreshCw className={`h-4 w-4 ${busy ? "animate-spin" : ""}`} />Recalculate</Button><Button onClick={generate} disabled={!canGenerate || busy || !selected.length}><FilePlus2 className="h-4 w-4" />Generate draft PO ({selected.length})</Button></>} />
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Critical shortage" value={summary.critical || 0} icon={TriangleAlert} tone="red" /><StatCard label="Reorder required" value={summary.required || 0} icon={Calculator} /><StatCard label="Estimated purchase" value={<Money value={summary.value} />} icon={CircleDollarSign} tone="green" /><StatCard label="Missing configuration" value={summary.missing || 0} icon={Settings2} tone="amber" /><StatCard label="Stale suggestions" value={summary.stale || 0} icon={AlertTriangle} tone="violet" /></section>
    <section className={`${cardClass} mt-4`}><div className="grid gap-3 border-b border-white/10 p-4 md:grid-cols-[minmax(220px,1fr)_220px_220px]"><input className={inputClass} value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search item or SKU…" /><DarkSelect className={inputClass} value={severity} onChange={(event) => { setSeverity(event.target.value); setPage(1); }}><option value="">All severities</option>{["critical", "high", "medium", "low"].map((value) => <option key={value}>{value}</option>)}</DarkSelect><DarkSelect className={inputClass} value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All statuses</option>{["open", "reviewed", "dismissed", "converted", "resolved", "stale"].map((value) => <option key={value}>{value}</option>)}</DarkSelect></div>{loading ? <LoadingState /> : <DataTable columns={columns} rows={data?.data} empty={<EmptyState title="No reorder suggestions" description="Enable reorder automation on stock items, then run a recalculation." />} />}<Pagination pagination={data?.pagination} onPageChange={setPage} /></section>
    <Modal open={Boolean(details)} onClose={() => setDetails(null)} title={`Calculation · ${details?.item?.name || ""}`} description={`Calculated ${formatDate(details?.calculatedAt, true)}`}><div className="grid gap-3 sm:grid-cols-2">{details && Object.entries(details.breakdown || {}).map(([key, value]) => typeof value !== "object" && <div key={key} className="rounded-xl border border-white/10 bg-black/20 p-3"><p className="text-[0.65rem] uppercase tracking-wide text-neutral-600">{humanize(key)}</p><p className="mt-1 text-sm text-white">{String(value ?? "—")}</p></div>)}</div>{details?.warnings?.length > 0 && <div className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/5 p-4"><p className="text-xs font-semibold text-amber-300">Warnings</p><p className="mt-2 text-xs text-neutral-400">{details.warnings.map(humanize).join(" · ")}</p></div>}</Modal>
    <Modal open={Boolean(review)} onClose={() => setReview(null)} title="Review reorder suggestion" description="Changing quantity, supplier or price requires an audit reason."><form className="space-y-4" onSubmit={saveReview}><Field label="Purchase quantity"><input className={inputClass} type="number" min="0.000001" step="any" value={reviewForm.quantity} onChange={(event) => setReviewForm({ ...reviewForm, quantity: event.target.value })} /></Field><Field label="Supplier"><DarkSelect className={inputClass} value={reviewForm.supplier} onChange={(event) => setReviewForm({ ...reviewForm, supplier: event.target.value })}><option value="">Choose supplier</option>{suppliers.map((row) => <option key={row._id} value={row._id}>{row.name}</option>)}</DarkSelect></Field><Field label="Manual unit price (SAR, optional)" hint="Leave blank to use posted invoice, received or approved price history."><input className={inputClass} type="number" min="0.01" step="0.01" value={reviewForm.unitPrice} onChange={(event) => setReviewForm({ ...reviewForm, unitPrice: event.target.value })} /></Field><Field label="Override reason"><textarea className={textareaClass} value={reviewForm.reason} onChange={(event) => setReviewForm({ ...reviewForm, reason: event.target.value })} /></Field><div className="flex justify-end"><Button type="submit" disabled={busy}>Save review</Button></div></form></Modal>
  </div>;
}
