"use client";
import RecordId from "@/src/components/ui/RecordId.jsx";

import { useEffect, useState } from "react";
import SupplierInvoiceForm from "./SupplierInvoiceForm.jsx";
import { useAuth } from "@/src/context/AuthContext.jsx";
import { BadgeDollarSign, Check, Eye, FileCheck2, Pencil, Plus, Send, XCircle } from "lucide-react";
import { toast } from "sonner";
import SupplierPaymentForm from "./SupplierPaymentForm.jsx";
import { pendingSubmission, submissionStorageKey } from "@/src/utils/persistedSubmission.js";
import DarkSelect from "@/src/components/ui/DarkSelect.jsx";
import { createSupplierInvoice, reverseSupplierPayment, fetchPurchaseOrders, fetchSupplierInvoice, fetchSupplierInvoices, fetchSuppliers, updateSupplierInvoice, updateSupplierInvoiceStatus } from "@/src/api/inventoryApi.js";
import { Badge, Button, DataTable, EmptyState, LoadingState, Modal, Money, PageHeader, Pagination, StatCard, cardClass, inputClass } from "./InventoryUI.jsx";
import { apiErrorMessage, formatDate, humanize } from "./inventoryUtils.js";
import useInventoryResource from "./useInventoryResource.js";

const tones = { draft: "info", submitted: "warning", review_required: "danger", approved: "success", posted: "success", disputed: "danger", voided: "neutral", unpaid: "danger", partially_paid: "warning", paid: "success", overdue: "danger" };

export default function SupplierInvoicesPage() {
  const { user } = useAuth();
  const manager = ["admin", "manager"].includes(user?.role);
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [status, setStatus] = useState(""); const [paymentStatus, setPaymentStatus] = useState("");
  const [suppliers, setSuppliers] = useState([]); const [orders, setOrders] = useState([]); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState(null); const [detail, setDetail] = useState(null); const [paymentFor, setPaymentFor] = useState(null); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { Promise.all([fetchSuppliers(), fetchPurchaseOrders({ limit: 100 })]).then(([supplierRows, poRows]) => { setSuppliers(supplierRows); setOrders(poRows.data.filter((row) => ["ordered", "partially_received", "received", "closed_short"].includes(row.status))); }).catch(() => toast.error("Unable to load invoice options.")); }, []);
  const { data, loading, error, reload } = useInventoryResource(() => fetchSupplierInvoices({ page, limit: 20, status: status || undefined, paymentStatus: paymentStatus || undefined, search }), [page, status, paymentStatus, search]);
  const save = async (payload) => { setSubmitting(true); try { if (editing) await updateSupplierInvoice(editing._id, payload); else await createSupplierInvoice(payload); toast.success(editing ? "Supplier invoice updated." : "Supplier invoice created as draft."); setFormOpen(false); setEditing(null); reload({ silent: true }); } catch (error) { toast.error(apiErrorMessage(error)); } finally { setSubmitting(false); } };
  const transition = async (row, target) => { const reason = ["voided", "disputed"].includes(target) || (["submitted", "approved", "posted"].includes(target) && Number(row.matchSummary?.mismatches || 0) > 0) ? window.prompt("Reason / review note") : ""; if (reason === null) return; try { await updateSupplierInvoiceStatus(row._id, target, { reason, idempotencyKey: crypto.randomUUID() }); toast.success(`Invoice ${humanize(target)}.`); reload({ silent: true }); } catch (error) { toast.error(apiErrorMessage(error)); } };
  const openDetail = async (row) => { try { setDetail(await fetchSupplierInvoice(row._id)); } catch (error) { toast.error(apiErrorMessage(error)); } };
  const hasPendingPayment = row => { try { return Boolean(pendingSubmission(localStorage, submissionStorageKey("supplier-payment", user?._id, row._id))); } catch { return true; } };
  const reversePayment = async row => { const reason = window.prompt("Reason for reversing this recorded payment"); if (!reason?.trim()) return; try { await reverseSupplierPayment(row._id, reason); toast.success("Payment reversed."); setDetail(await fetchSupplierInvoice(detail.data._id)); await reload({ silent: true }); } catch (failure) { toast.error(apiErrorMessage(failure)); } };
  const columns = [{ key: "reference", label: "Invoice", render: (row) => <div><p className="font-semibold text-white"><RecordId value={row.internalReference} /></p><p className="text-[0.65rem] text-neutral-600"><RecordId value={row.supplierInvoiceNumber} /></p></div> }, { key: "supplier", label: "Supplier", render: (row) => row.supplier?.name }, { key: "date", label: "Invoice / due", render: (row) => <div>{formatDate(row.invoiceDate)}<p className="text-[0.65rem] text-neutral-600">Due {formatDate(row.dueDate)}</p></div> }, { key: "total", label: "Total", render: (row) => <Money value={row.total} /> }, { key: "outstanding", label: "Outstanding", render: (row) => <Money value={row.outstandingAmount} /> }, { key: "match", label: "Match", render: (row) => <Badge tone={row.matchSummary?.mismatches ? "danger" : "success"}>{row.matchSummary?.mismatches ? `${row.matchSummary.mismatches} mismatch` : "Matched"}</Badge> }, { key: "status", label: "Status", render: (row) => <div className="space-y-1"><Badge tone={tones[row.status]}>{humanize(row.status)}</Badge><Badge tone={tones[row.displayPaymentStatus]}>{humanize(row.displayPaymentStatus)}</Badge></div> }, { key: "actions", label: "", render: (row) => <div className="flex justify-end gap-1">{["draft", "review_required"].includes(row.status) && <button onClick={() => { setEditing(row); setFormOpen(true); }} className="p-2 text-neutral-400" title="Edit draft"><Pencil className="h-4 w-4" /></button>}{row.status === "draft" && <button onClick={() => transition(row, "submitted")} className="p-2 text-amber-400" title="Submit"><Send className="h-4 w-4" /></button>}{manager && ["submitted", "review_required"].includes(row.status) && <button onClick={() => transition(row, "approved")} className="p-2 text-emerald-400" title="Approve"><Check className="h-4 w-4" /></button>}{manager && row.status === "approved" && <button onClick={() => transition(row, "posted")} className="p-2 text-emerald-400" title="Post"><FileCheck2 className="h-4 w-4" /></button>}{row.status === "posted" && (row.paymentStatus !== "paid" || hasPendingPayment(row)) && <button onClick={() => setPaymentFor(row)} className="p-2 text-dune-amber" title="Record payment"><BadgeDollarSign className="h-4 w-4" /></button>}{manager && row.status !== "voided" && <button onClick={() => transition(row, "voided")} className="p-2 text-red-400" title="Void and release billable reservation"><XCircle className="h-4 w-4" /></button>}<button onClick={() => openDetail(row)} className="p-2 text-neutral-400" title="View"><Eye className="h-4 w-4" /></button></div> }];
  const aging = data?.aging || {};
  return <div className="mx-auto max-w-[1600px]"><PageHeader title="Supplier Invoices & Payables" description="Three-way match purchase orders, receipts and supplier invoices. Operating expenses remain separate." actions={<Button onClick={() => setFormOpen(true)}><Plus className="h-4 w-4" />Add invoice</Button>} /><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Current" value={<Money value={aging.current} />} /><StatCard label="1–30 days" value={<Money value={aging.days1to30} />} tone="amber" /><StatCard label="31–60 days" value={<Money value={aging.days31to60} />} tone="orange" /><StatCard label="61–90 days" value={<Money value={aging.days61to90} />} tone="red" /><StatCard label="90+ days" value={<Money value={aging.days90plus} />} tone="violet" /></div><section className={cardClass}><label className="block p-4 text-xs text-neutral-400">Search internal / supplier invoice ID<input type="search" value={search} onChange={event => { setSearch(event.target.value); setPage(1); }} className={`${inputClass} mt-2`} /></label><div className="flex flex-wrap gap-3 border-b border-white/10 p-4"><DarkSelect className={`${inputClass} w-52`} value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All invoice statuses</option>{["draft", "submitted", "review_required", "approved", "posted", "disputed", "voided"].map((value) => <option key={value} value={value}>{humanize(value)}</option>)}</DarkSelect><DarkSelect className={`${inputClass} w-52`} value={paymentStatus} onChange={(event) => { setPaymentStatus(event.target.value); setPage(1); }}><option value="">All payment statuses</option>{["unpaid", "partially_paid", "paid"].map((value) => <option key={value} value={value}>{humanize(value)}</option>)}</DarkSelect></div>{error ? <div role="alert" className="p-5 text-red-300">Unable to refresh invoices. Figures may be stale. <Button onClick={() => reload().catch(() => undefined)}>Retry</Button></div> : loading ? <LoadingState /> : <DataTable columns={columns} rows={data?.data} empty={<EmptyState title="No supplier invoices" />} />}<Pagination pagination={data?.pagination} onPageChange={setPage} /></section>
    <Modal open={formOpen} onClose={() => { setFormOpen(false); setEditing(null); }} title={editing ? `Edit ${editing.internalReference}` : "Create supplier invoice"} description="Totals and PO/receipt matching are recalculated by the server." maxWidth="max-w-5xl"><SupplierInvoiceForm key={editing?._id || "new"} invoice={editing} suppliers={suppliers} orders={orders} onSubmit={save} submitting={submitting} /></Modal>
    <Modal open={Boolean(paymentFor)} onClose={() => setPaymentFor(null)} title={`Record payment · ${paymentFor?.internalReference || ""}`}>{paymentFor && <SupplierPaymentForm key={paymentFor._id} invoice={paymentFor} actorId={user?._id} onComplete={async () => { toast.success("Supplier payment confirmed."); setPaymentFor(null); await reload({ silent: true }).catch(() => undefined); }} />}</Modal>
    <Modal open={Boolean(detail)} onClose={() => setDetail(null)} title={detail?.data?.internalReference || "Invoice details"} maxWidth="max-w-4xl">{detail?.data && <div className="space-y-4"><RecordId value={detail.data.internalReference} /> · <RecordId value={detail.data.supplierInvoiceNumber} /><div className="grid gap-3 sm:grid-cols-3"><StatCard label="Invoice total" value={<Money value={detail.data.total} />} /><StatCard label="Paid" value={<Money value={detail.data.paidAmount} />} tone="green" /><StatCard label="Outstanding" value={<Money value={detail.data.outstandingAmount} />} tone="red" /></div><section><h3 className="mb-2 text-sm font-semibold text-white">Invoice lines</h3><div className="space-y-2">{detail.data.items.map((row) => <div key={row._id} className="grid gap-2 rounded-xl border border-white/10 p-3 text-xs sm:grid-cols-[1fr_.8fr_.6fr]"><span className="font-medium text-white">{row.item?.name || "Inventory item"}<span className="mt-1 block font-normal text-neutral-400">Quantity {row.quantity} {row.unit}</span></span><span><span className="text-neutral-600">Brand: </span>{row.brand || "Not recorded"}</span><span className="text-right"><Money value={row.lineTotal} /></span></div>)}</div></section>{detail.data.matchSummary?.quantityChecks?.map(row => <p key={row.purchaseOrderLine} className="text-xs text-neutral-400">{row.itemName}: received {row.receivedQuantity}, committed elsewhere {row.committedQuantity}, remaining billable {row.remainingBillableQuantity} (last validation snapshot).</p>)}{detail.data.matchSummary?.messages?.length > 0 && <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-xs text-red-200">{detail.data.matchSummary.messages.map((message) => <p key={message}>{message}</p>)}</div>}<h3 className="text-sm font-semibold text-white">Payment history</h3>{detail.payments?.length ? detail.payments.map((row) => <div key={row._id} className="flex justify-between rounded-xl border border-white/10 p-3 text-xs"><span><RecordId value={row.paymentNumber} /><br />{formatDate(row.paymentDate)} · {humanize(row.method)}</span><span><Money value={row.amountHalala / 100} /> · {humanize(row.status)}{manager && row.status === "completed" && <Button onClick={() => reversePayment(row)}>Reverse payment</Button>}</span></div>) : <p className="text-xs text-neutral-600">No payments recorded.</p>}</div>}</Modal>
  </div>;
}
