"use client";

import { useEffect, useMemo, useState } from "react";
import { BadgeDollarSign, Check, Eye, FileCheck2, Pencil, Plus, Send } from "lucide-react";
import { toast } from "sonner";
import DarkDatePicker from "@/src/components/ui/DarkDatePicker.jsx";
import DarkSelect from "@/src/components/ui/DarkSelect.jsx";
import { createSupplierInvoice, createSupplierPayment, fetchPurchaseOrders, fetchSupplierInvoice, fetchSupplierInvoices, fetchSuppliers, updateSupplierInvoice, updateSupplierInvoiceStatus } from "@/src/api/inventoryApi.js";
import { Badge, Button, DataTable, EmptyState, Field, LoadingState, Modal, Money, PageHeader, Pagination, StatCard, cardClass, inputClass, textareaClass } from "./InventoryUI.jsx";
import { apiErrorMessage, formatDate, humanize } from "./inventoryUtils.js";
import useInventoryResource from "./useInventoryResource.js";

const tones = { draft: "info", submitted: "warning", review_required: "danger", approved: "success", posted: "success", disputed: "danger", voided: "neutral", unpaid: "danger", partially_paid: "warning", paid: "success", overdue: "danger" };

function InvoiceForm({ invoice, suppliers, orders, onSubmit, submitting }) {
  const [form, setForm] = useState(() => invoice ? { supplier: invoice.supplier?._id || invoice.supplier, supplierInvoiceNumber: invoice.supplierInvoiceNumber, purchaseOrder: invoice.purchaseOrders?.[0]?._id || invoice.purchaseOrders?.[0] || "", invoiceDate: new Date(invoice.invoiceDate).toISOString().slice(0, 10), dueDate: invoice.dueDate ? new Date(invoice.dueDate).toISOString().slice(0, 10) : "", tax: invoice.tax || 0, discount: invoice.discount || 0, additionalCharges: invoice.additionalCharges || 0, note: invoice.note || "", items: invoice.items.map((row) => ({ item: row.item?._id || row.item, purchaseOrder: row.purchaseOrder?._id || row.purchaseOrder, purchaseOrderLine: row.purchaseOrderLine, quantity: row.quantity, unitPrice: row.unitPrice, tax: row.tax || 0, discount: row.discount || 0, name: row.item?.name || "Inventory item", unit: row.unit })) } : { supplier: "", supplierInvoiceNumber: "", purchaseOrder: "", invoiceDate: new Date().toISOString().slice(0, 10), dueDate: "", tax: 0, discount: 0, additionalCharges: 0, note: "", items: [] });
  const availableOrders = orders.filter((row) => !form.supplier || String(row.supplier?._id || row.supplier) === form.supplier);
  const chooseOrder = (id) => { const order = orders.find((row) => row._id === id); setForm((current) => { const existing = new Set(current.items.map((line) => String(line.purchaseOrderLine))); const added = order ? order.items.filter((line) => !existing.has(String(line._id))).map((line) => ({ item: line.item?._id || line.item, purchaseOrder: order._id, purchaseOrderLine: line._id, quantity: Number(line.receivedQuantity || line.quantity), unitPrice: Number(line.unitCost), tax: 0, discount: 0, name: line.itemName, unit: line.purchaseUnit || line.baseUnit })) : []; return { ...current, purchaseOrder: id, supplier: String(order?.supplier?._id || order?.supplier || current.supplier), items: [...current.items, ...added] }; }); };
  const subtotal = useMemo(() => form.items.reduce((sum, row) => sum + Number(row.quantity || 0) * Number(row.unitPrice || 0), 0), [form.items]);
  const line = (index, field, value) => setForm((current) => ({ ...current, items: current.items.map((row, rowIndex) => rowIndex === index ? { ...row, [field]: value } : row) }));
  const submit = (event) => { event.preventDefault(); onSubmit({ ...form, dueDate: form.dueDate || null, tax: Number(form.tax), discount: Number(form.discount), additionalCharges: Number(form.additionalCharges), items: form.items.map(({ name, unit, ...row }) => ({ ...row, quantity: Number(row.quantity), unitPrice: Number(row.unitPrice), tax: Number(row.tax || 0), discount: Number(row.discount || 0) })) }); };
  return <form onSubmit={submit} className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Field label="Supplier"><DarkSelect required className={inputClass} value={form.supplier} onChange={(event) => setForm({ ...form, supplier: event.target.value, purchaseOrder: "", items: [] })}><option value="">Choose supplier</option>{suppliers.map((row) => <option key={row._id} value={row._id}>{row.name}</option>)}</DarkSelect></Field><Field label="Supplier invoice number"><input required className={inputClass} value={form.supplierInvoiceNumber} onChange={(event) => setForm({ ...form, supplierInvoiceNumber: event.target.value })} /></Field><Field label="Purchase order"><DarkSelect required className={inputClass} value={form.purchaseOrder} onChange={(event) => chooseOrder(event.target.value)}><option value="">Choose received PO</option>{availableOrders.map((row) => <option key={row._id} value={row._id}>{row.orderNumber} · {humanize(row.status)}</option>)}</DarkSelect></Field><Field label="Invoice date"><DarkDatePicker required className={inputClass} value={form.invoiceDate} onChange={(event) => setForm({ ...form, invoiceDate: event.target.value })} /></Field><Field label="Due date"><DarkDatePicker className={inputClass} value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} /></Field></div>
    <div className="space-y-2">{form.items.map((row, index) => <div key={row.purchaseOrderLine} className="grid gap-3 rounded-xl border border-white/10 bg-black/20 p-3 sm:grid-cols-[1fr_.55fr_.65fr_.5fr]"><Field label="Item"><input disabled className={inputClass} value={`${row.name} · ${row.unit}`} /></Field><Field label="Invoice qty"><input required min="0.0001" step="any" type="number" className={inputClass} value={row.quantity} onChange={(event) => line(index, "quantity", event.target.value)} /></Field><Field label="Unit price (SAR)"><input required min="0" step="0.01" type="number" className={inputClass} value={row.unitPrice} onChange={(event) => line(index, "unitPrice", event.target.value)} /></Field><Field label="Line total"><div className={`${inputClass} flex items-center`}><Money value={Number(row.quantity || 0) * Number(row.unitPrice || 0)} /></div></Field></div>)}</div>
    <div className="grid gap-3 sm:grid-cols-3"><Field label="Tax (SAR)"><input min="0" step="0.01" type="number" className={inputClass} value={form.tax} onChange={(event) => setForm({ ...form, tax: event.target.value })} /></Field><Field label="Discount (SAR)"><input min="0" step="0.01" type="number" className={inputClass} value={form.discount} onChange={(event) => setForm({ ...form, discount: event.target.value })} /></Field><Field label="Shipping / charges"><input min="0" step="0.01" type="number" className={inputClass} value={form.additionalCharges} onChange={(event) => setForm({ ...form, additionalCharges: event.target.value })} /></Field></div><Field label="Notes"><textarea className={textareaClass} value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} /></Field><div className="flex items-center justify-between"><p className="text-sm text-neutral-400">Estimated total: <strong className="text-dune-amber"><Money value={subtotal + Number(form.tax) + Number(form.additionalCharges) - Number(form.discount)} /></strong></p><Button type="submit" disabled={submitting || !form.items.length}>{submitting ? "Saving…" : "Create invoice"}</Button></div></form>;
}

export default function SupplierInvoicesPage() {
  const [page, setPage] = useState(1); const [status, setStatus] = useState(""); const [paymentStatus, setPaymentStatus] = useState("");
  const [suppliers, setSuppliers] = useState([]); const [orders, setOrders] = useState([]); const [formOpen, setFormOpen] = useState(false); const [editing, setEditing] = useState(null); const [detail, setDetail] = useState(null); const [paymentFor, setPaymentFor] = useState(null); const [payment, setPayment] = useState({ amount: "", method: "bank_transfer", transactionReference: "", paymentDate: new Date().toISOString().slice(0, 10), note: "" }); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { Promise.all([fetchSuppliers(), fetchPurchaseOrders({ limit: 100 })]).then(([supplierRows, poRows]) => { setSuppliers(supplierRows); setOrders(poRows.data.filter((row) => ["ordered", "partially_received", "received", "closed_short"].includes(row.status))); }).catch(() => toast.error("Unable to load invoice options.")); }, []);
  const { data, loading, reload } = useInventoryResource(() => fetchSupplierInvoices({ page, limit: 20, status: status || undefined, paymentStatus: paymentStatus || undefined }), [page, status, paymentStatus]);
  const save = async (payload) => { setSubmitting(true); try { if (editing) await updateSupplierInvoice(editing._id, payload); else await createSupplierInvoice(payload); toast.success(editing ? "Supplier invoice updated." : "Supplier invoice created as draft."); setFormOpen(false); setEditing(null); reload({ silent: true }); } catch (error) { toast.error(apiErrorMessage(error)); } finally { setSubmitting(false); } };
  const transition = async (row, target) => { const reason = ["approved", "voided", "disputed"].includes(target) && (row.status === "review_required" || target !== "approved") ? window.prompt("Reason / review note") : ""; if (reason === null) return; try { await updateSupplierInvoiceStatus(row._id, target, { reason, idempotencyKey: crypto.randomUUID() }); toast.success(`Invoice ${humanize(target)}.`); reload({ silent: true }); } catch (error) { toast.error(apiErrorMessage(error)); } };
  const openDetail = async (row) => { try { setDetail(await fetchSupplierInvoice(row._id)); } catch (error) { toast.error(apiErrorMessage(error)); } };
  const pay = async (event) => { event.preventDefault(); setSubmitting(true); try { await createSupplierPayment(paymentFor._id, { ...payment, amount: Number(payment.amount), idempotencyKey: crypto.randomUUID() }); toast.success("Supplier payment recorded."); setPaymentFor(null); reload({ silent: true }); } catch (error) { toast.error(apiErrorMessage(error)); } finally { setSubmitting(false); } };
  const columns = [{ key: "reference", label: "Invoice", render: (row) => <div><p className="font-semibold text-white">{row.internalReference}</p><p className="text-[0.65rem] text-neutral-600">{row.supplierInvoiceNumber}</p></div> }, { key: "supplier", label: "Supplier", render: (row) => row.supplier?.name }, { key: "date", label: "Invoice / due", render: (row) => <div>{formatDate(row.invoiceDate)}<p className="text-[0.65rem] text-neutral-600">Due {formatDate(row.dueDate)}</p></div> }, { key: "total", label: "Total", render: (row) => <Money value={row.total} /> }, { key: "outstanding", label: "Outstanding", render: (row) => <Money value={row.outstandingAmount} /> }, { key: "match", label: "Match", render: (row) => <Badge tone={row.matchSummary?.mismatches ? "danger" : "success"}>{row.matchSummary?.mismatches ? `${row.matchSummary.mismatches} mismatch` : "Matched"}</Badge> }, { key: "status", label: "Status", render: (row) => <div className="space-y-1"><Badge tone={tones[row.status]}>{humanize(row.status)}</Badge><Badge tone={tones[row.displayPaymentStatus]}>{humanize(row.displayPaymentStatus)}</Badge></div> }, { key: "actions", label: "", render: (row) => <div className="flex justify-end gap-1">{["draft", "review_required"].includes(row.status) && <button onClick={() => { setEditing(row); setFormOpen(true); }} className="p-2 text-neutral-400" title="Edit draft"><Pencil className="h-4 w-4" /></button>}{row.status === "draft" && <button onClick={() => transition(row, "submitted")} className="p-2 text-amber-400" title="Submit"><Send className="h-4 w-4" /></button>}{["submitted", "review_required"].includes(row.status) && <button onClick={() => transition(row, "approved")} className="p-2 text-emerald-400" title="Approve"><Check className="h-4 w-4" /></button>}{row.status === "approved" && <button onClick={() => transition(row, "posted")} className="p-2 text-emerald-400" title="Post"><FileCheck2 className="h-4 w-4" /></button>}{row.status === "posted" && row.paymentStatus !== "paid" && <button onClick={() => { setPaymentFor(row); setPayment((current) => ({ ...current, amount: row.outstandingAmount })); }} className="p-2 text-dune-amber" title="Record payment"><BadgeDollarSign className="h-4 w-4" /></button>}<button onClick={() => openDetail(row)} className="p-2 text-neutral-400" title="View"><Eye className="h-4 w-4" /></button></div> }];
  const aging = data?.aging || {};
  return <div className="mx-auto max-w-[1600px]"><PageHeader title="Supplier Invoices & Payables" description="Three-way match purchase orders, receipts and supplier invoices. Operating expenses remain separate." actions={<Button onClick={() => setFormOpen(true)}><Plus className="h-4 w-4" />Add invoice</Button>} /><div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Current" value={<Money value={aging.current} />} /><StatCard label="1–30 days" value={<Money value={aging.days1to30} />} tone="amber" /><StatCard label="31–60 days" value={<Money value={aging.days31to60} />} tone="orange" /><StatCard label="61–90 days" value={<Money value={aging.days61to90} />} tone="red" /><StatCard label="90+ days" value={<Money value={aging.days90plus} />} tone="violet" /></div><section className={cardClass}><div className="flex flex-wrap gap-3 border-b border-white/10 p-4"><DarkSelect className={`${inputClass} w-52`} value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All invoice statuses</option>{["draft", "submitted", "review_required", "approved", "posted", "disputed", "voided"].map((value) => <option key={value} value={value}>{humanize(value)}</option>)}</DarkSelect><DarkSelect className={`${inputClass} w-52`} value={paymentStatus} onChange={(event) => { setPaymentStatus(event.target.value); setPage(1); }}><option value="">All payment statuses</option>{["unpaid", "partially_paid", "paid"].map((value) => <option key={value}>{humanize(value)}</option>)}</DarkSelect></div>{loading ? <LoadingState /> : <DataTable columns={columns} rows={data?.data} empty={<EmptyState title="No supplier invoices" />} />}<Pagination pagination={data?.pagination} onPageChange={setPage} /></section>
    <Modal open={formOpen} onClose={() => { setFormOpen(false); setEditing(null); }} title={editing ? `Edit ${editing.internalReference}` : "Create supplier invoice"} description="Totals and PO/receipt matching are recalculated by the server." maxWidth="max-w-5xl"><InvoiceForm key={editing?._id || "new"} invoice={editing} suppliers={suppliers} orders={orders} onSubmit={save} submitting={submitting} /></Modal>
    <Modal open={Boolean(paymentFor)} onClose={() => setPaymentFor(null)} title={`Record payment · ${paymentFor?.internalReference || ""}`}><form onSubmit={pay} className="space-y-4"><Field label="Amount (SAR)"><input required min="0.01" max={paymentFor?.outstandingAmount} step="0.01" type="number" className={inputClass} value={payment.amount} onChange={(event) => setPayment({ ...payment, amount: event.target.value })} /></Field><Field label="Method"><DarkSelect className={inputClass} value={payment.method} onChange={(event) => setPayment({ ...payment, method: event.target.value })}>{["bank_transfer", "cash", "card", "cheque", "other"].map((value) => <option key={value} value={value}>{humanize(value)}</option>)}</DarkSelect></Field><Field label="Payment date"><DarkDatePicker className={inputClass} value={payment.paymentDate} onChange={(event) => setPayment({ ...payment, paymentDate: event.target.value })} /></Field><Field label="Transaction reference"><input className={inputClass} value={payment.transactionReference} onChange={(event) => setPayment({ ...payment, transactionReference: event.target.value })} /></Field><Field label="Note"><textarea className={textareaClass} value={payment.note} onChange={(event) => setPayment({ ...payment, note: event.target.value })} /></Field><Button type="submit" disabled={submitting}>Record payment</Button></form></Modal>
    <Modal open={Boolean(detail)} onClose={() => setDetail(null)} title={detail?.data?.internalReference || "Invoice details"} maxWidth="max-w-4xl">{detail?.data && <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><StatCard label="Invoice total" value={<Money value={detail.data.total} />} /><StatCard label="Paid" value={<Money value={detail.data.paidAmount} />} tone="green" /><StatCard label="Outstanding" value={<Money value={detail.data.outstandingAmount} />} tone="red" /></div>{detail.data.matchSummary?.messages?.length > 0 && <div className="rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-xs text-red-200">{detail.data.matchSummary.messages.map((message) => <p key={message}>{message}</p>)}</div>}<h3 className="text-sm font-semibold text-white">Payment history</h3>{detail.payments?.length ? detail.payments.map((row) => <div key={row._id} className="flex justify-between rounded-xl border border-white/10 p-3 text-xs"><span>{formatDate(row.paymentDate)} · {humanize(row.method)}</span><span><Money value={row.amountHalala / 100} /> · {humanize(row.status)}</span></div>) : <p className="text-xs text-neutral-600">No payments recorded.</p>}</div>}</Modal>
  </div>;
}
