"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, Download, PackageX, Plus, Search, Trash2, TrendingDown } from "lucide-react";
import { toast } from "sonner";
import { createWasteRecord, fetchInventoryCategories, fetchInventoryItems, fetchWasteRecords } from "@/src/api/inventoryApi.js";
import { Badge, Button, DataTable, EmptyState, LoadingState, Modal, Money, PageHeader, Pagination, StatCard, cardClass, inputClass } from "./InventoryUI.jsx";
import { apiErrorMessage, downloadCsv, formatDate, formatQuantity, formatSar, humanize } from "./inventoryUtils.js";
import WasteRecordForm from "./WasteRecordForm.jsx";
import useInventoryResource from "./useInventoryResource.js";

const reasons = ["SPOILED", "EXPIRED", "BROKEN", "DAMAGED_PACKAGE", "SPILLAGE", "OVERCOOKED", "OTHER"];

export default function WasteDamagedPage() {
  const [search, setSearch] = useState(""); const [debouncedSearch, setDebouncedSearch] = useState("");
  const [reasonCode, setReasonCode] = useState(""); const [category, setCategory] = useState(""); const [user, setUser] = useState("");
  const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [page, setPage] = useState(1);
  const [items, setItems] = useState([]); const [categories, setCategories] = useState([]); const [modalOpen, setModalOpen] = useState(false); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { const timeout = setTimeout(() => { setDebouncedSearch(search.trim()); setPage(1); }, 250); return () => clearTimeout(timeout); }, [search]);
  const loadMetadata = () => Promise.all([fetchInventoryItems({ limit: 100, sortBy: "name", sortOrder: "asc" }), fetchInventoryCategories()]).then(([itemResponse, categoryRows]) => { setItems(itemResponse.data); setCategories(categoryRows); });
  useEffect(() => { loadMetadata().catch(() => toast.error("Unable to load waste form options.")); }, []);
  const { data, loading, error, reload } = useInventoryResource(() => fetchWasteRecords({ page, limit: 20, search: debouncedSearch || undefined, reasonCode: reasonCode || undefined, category: category || undefined, user: user || undefined, from: from || undefined, to: to || undefined }), [page, debouncedSearch, reasonCode, category, user, from, to]);
  const submit = async (payload) => { setSubmitting(true); try { await createWasteRecord(payload); toast.success("Waste / damaged stock recorded and inventory history updated."); setModalOpen(false); await Promise.all([reload({ silent: true }), loadMetadata()]); return true; } catch (submitError) { toast.error(apiErrorMessage(submitError, "Unable to record stock loss.")); return false; } finally { setSubmitting(false); } };
  const clearFilters = () => { setSearch(""); setReasonCode(""); setCategory(""); setUser(""); setFrom(""); setTo(""); setPage(1); };
  const rows = data?.data || [];
  const columns = useMemo(() => [
    { key: "item", label: "Item", render: (row) => <div><p className="font-medium text-white">{row.item?.name || "Archived item"}</p><p className="text-[0.65rem] text-neutral-600">{row.item?.sku || "—"}</p></div> },
    { key: "category", label: "Category", render: (row) => row.item?.category?.name || "—" },
    { key: "quantity", label: "Quantity lost", render: (row) => formatQuantity(row.quantity, row.item?.unit) },
    { key: "reason", label: "Reason", render: (row) => <Badge tone={row.movementType === "DAMAGED" ? "warning" : "danger"}>{humanize(row.reasonCode || row.reason)}</Badge> },
    { key: "cost", label: "Cost impact", render: (row) => <span className="text-red-300"><Money value={row.costImpact} /></span> },
    { key: "user", label: "Recorded by", render: (row) => row.user?.name || "—" },
    { key: "date", label: "Date", render: (row) => formatDate(row.occurredAt, true) },
    { key: "reference", label: "Reference", render: (row) => row.reference || "—" },
    { key: "status", label: "Status", render: (row) => <Badge tone="success">{humanize(row.status || "COMPLETED")}</Badge> },
  ], []);
  const exportCsv = () => { if (!rows.length) return toast.error("There are no records to export."); downloadCsv(`waste-damaged-${new Date().toISOString().slice(0, 10)}.csv`, [["Date", (row) => new Date(row.occurredAt).toISOString()], ["Item", (row) => row.item?.name], ["SKU", (row) => row.item?.sku], ["Type", (row) => row.movementType], ["Quantity", (row) => row.quantity], ["Unit", (row) => row.item?.unit], ["Reason", (row) => row.reasonCode || row.reason], ["Cost SAR", (row) => row.costImpact], ["Recorded By", (row) => row.user?.name], ["Reference", (row) => row.reference]], rows); };
  const summary = data?.summary || {};
  const maxReasonCost = Math.max(...(data?.reasonBreakdown || []).map((row) => Number(row.cost || 0)), 1);
  return <div className="mx-auto max-w-[1800px]">
    <PageHeader eyebrow="Waste / Damaged" title="Waste / Damaged Stock" description="Record spoiled, expired, broken and damaged inventory through the audited stock ledger." actions={<><Button variant="secondary" onClick={exportCsv}><Download className="h-4 w-4" />Export Report</Button><Button onClick={() => setModalOpen(true)}><Plus className="h-4 w-4" />Record Loss</Button></>} />
    <div className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Waste Today" value={formatQuantity(summary.todayQuantity || 0)} caption={formatSar(summary.todayCost)} icon={Trash2} tone="red" /><StatCard label="Waste This Week" value={formatQuantity(summary.weekQuantity || 0)} caption="Last 7 days" icon={CalendarDays} tone="green" /><StatCard label="Cost Impact This Week" value={formatSar(summary.weekCost || 0)} caption="Historic unit-cost snapshot" icon={TrendingDown} tone="red" /><StatCard label="Most Costly Item" value={summary.topItem?.item?.name || "—"} caption={summary.topItem ? `${formatQuantity(summary.topItem.quantity, summary.topItem.item?.unit)} · ${formatSar(summary.topItem.cost)}` : "No losses this week"} icon={PackageX} tone="violet" /></div>
    <div className="grid gap-4 2xl:grid-cols-[minmax(0,1fr)_330px]">
      <section className={cardClass}><div className="grid gap-3 border-b border-white/10 p-4 md:grid-cols-2 xl:grid-cols-[1.4fr_repeat(3,1fr)_0.9fr_0.9fr_auto]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-neutral-600" /><input className={`${inputClass} pl-10`} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search item, SKU or reference…" /></label><select className={inputClass} value={reasonCode} onChange={(event) => { setReasonCode(event.target.value); setPage(1); }}><option value="">All reasons</option>{reasons.map((reason) => <option key={reason} value={reason}>{humanize(reason)}</option>)}</select><select className={inputClass} value={category} onChange={(event) => { setCategory(event.target.value); setPage(1); }}><option value="">All categories</option>{categories.map((row) => <option key={row._id} value={row._id}>{row.name}</option>)}</select><select className={inputClass} value={user} onChange={(event) => { setUser(event.target.value); setPage(1); }}><option value="">All recorded by</option>{(data?.filters?.users || []).map((row) => <option key={row._id} value={row._id}>{row.name}</option>)}</select><input aria-label="From date" type="date" className={inputClass} value={from} onChange={(event) => { setFrom(event.target.value); setPage(1); }} /><input aria-label="To date" type="date" className={inputClass} value={to} onChange={(event) => { setTo(event.target.value); setPage(1); }} /><Button variant="secondary" onClick={clearFilters}>Reset</Button></div>{loading ? <LoadingState label="Loading waste records…" /> : error ? <EmptyState title="Unable to load records" description={apiErrorMessage(error)} action={<Button onClick={() => reload()}>Try again</Button>} /> : <DataTable columns={columns} rows={rows} empty={<EmptyState title="No waste or damaged records" description="Record a stock loss or change the current filters." action={<Button onClick={() => setModalOpen(true)}><Plus className="h-4 w-4" />Record first loss</Button>} />} />}<Pagination pagination={data?.pagination} onPageChange={setPage} /></section>
      <aside className="space-y-4"><section className={`${cardClass} p-4`}><h2 className="text-sm font-semibold text-white">Top Loss Reasons</h2><p className="mt-1 text-xs text-neutral-600">Last 7 days · by cost</p><div className="mt-4 space-y-3">{(data?.reasonBreakdown || []).map((row) => <div key={row._id}><div className="mb-1 flex items-center justify-between text-xs"><span className="text-neutral-300">{humanize(row._id)}</span><span className="text-neutral-500">{formatSar(row.cost)}</span></div><div className="h-2 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-gradient-to-r from-dune-amberDeep to-dune-amber" style={{ width: `${Math.max(4, (Number(row.cost) / maxReasonCost) * 100)}%` }} /></div></div>)}{!data?.reasonBreakdown?.length && <p className="py-6 text-center text-xs text-neutral-600">No loss data this week.</p>}</div></section><section className={`${cardClass} p-4`}><h2 className="text-sm font-semibold text-white">Recent Waste Activity</h2><div className="mt-3 divide-y divide-white/[0.06]">{(data?.recentActivity || []).map((row) => <div key={row._id} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><p className="truncate text-xs font-medium text-white">{row.item?.name || "Archived item"}</p><p className="mt-0.5 text-[0.65rem] text-neutral-600">{formatQuantity(row.quantity, row.item?.unit)} · {humanize(row.reasonCode || row.reason)}</p></div><span className="shrink-0 text-[0.65rem] text-neutral-600">{formatDate(row.occurredAt)}</span></div>)}</div></section></aside>
    </div>
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Record Waste / Damaged Stock" description="This will deduct stock and create a permanent movement entry." maxWidth="max-w-xl"><WasteRecordForm items={items} submitting={submitting} onSubmit={submit} /></Modal>
  </div>;
}
