import PurchasingAction from "../../models/PurchasingAction.js";
import { recordAuditLog } from "../../services/auditLogService.js";
import { refreshPurchasingActions } from "../../services/purchasingActionService.js";
import { escapeRegex, parsePagination, ValidationError } from "../../utils/inventoryValidation.js";

export const listPurchasingActions = async (req, res, next) => {
  try { const { page, limit, skip } = parsePagination(req.query); const filter = {}; const accountantTypes = ["SUPPLIER_INVOICE_MISMATCH", "PAYABLE_DUE_SOON", "PAYABLE_OVERDUE", "PURCHASE_PRICE_VARIANCE"]; const excludedOperationalTypes = ["PAYABLE_DUE_SOON", "PAYABLE_OVERDUE"]; if (req.user.role === "accountant") filter.actionType = req.query.actionType && accountantTypes.includes(req.query.actionType) ? req.query.actionType : { $in: accountantTypes }; else if (["inventory", "storekeeper"].includes(req.user.role)) filter.actionType = req.query.actionType && !excludedOperationalTypes.includes(req.query.actionType) ? req.query.actionType : { $nin: excludedOperationalTypes }; else if (req.query.actionType) filter.actionType = req.query.actionType; for (const field of ["state", "severity"]) if (req.query[field]) filter[field] = req.query[field]; if (req.query.search?.trim()) { const value = new RegExp(escapeRegex(req.query.search.trim()), "i"); filter.$or = [{ title: value }, { explanation: value }]; } const [rows, total, summary] = await Promise.all([PurchasingAction.find(filter).populate("acknowledgedBy snoozedBy", "name role").sort({ severity: 1, lastDetectedAt: -1 }).skip(skip).limit(limit).lean(), PurchasingAction.countDocuments(filter), PurchasingAction.aggregate([{ $match: filter }, { $group: { _id: "$state", count: { $sum: 1 } } }])]); res.json({ success: true, data: rows, summary: Object.fromEntries(summary.map((row) => [row._id, row.count])), pagination: { page, limit, total, pages: Math.ceil(total / limit) } }); } catch (error) { next(error); }
};

export const refreshActions = async (req, res, next) => { try { res.json({ success: true, data: await refreshPurchasingActions({ actor: req.user }) }); } catch (error) { next(error); } };

export const updateActionState = async (req, res, next) => {
  try { const row = await PurchasingAction.findById(req.params.id); if (!row) return res.status(404).json({ success: false, message: "Action not found" }); const state = req.body.state; if (!["acknowledged", "snoozed", "resolved"].includes(state)) throw new ValidationError("Invalid action state"); const reason = String(req.body.reason || "").trim(); if (state === "resolved" && !reason) throw new ValidationError("Resolution is required"); const before = { state: row.state, snoozedUntil: row.snoozedUntil }; row.state = state; if (state === "acknowledged") { row.acknowledgedBy = req.user._id; row.acknowledgedAt = new Date(); } if (state === "snoozed") { const hours = Math.max(1, Math.min(720, Number(req.body.hours) || 24)); row.snoozedBy = req.user._id; row.snoozedUntil = new Date(Date.now() + hours * 3600000); } if (state === "resolved") { row.resolvedAt = new Date(); row.resolution = reason; } await row.save(); await recordAuditLog({ actor: req.user, action: `PURCHASING_ACTION_${state.toUpperCase()}`, entityType: "PurchasingAction", entityId: row._id, entityLabel: row.title, reason, before, after: { state: row.state, snoozedUntil: row.snoozedUntil, resolution: row.resolution } }); res.json({ success: true, data: row }); } catch (error) { next(error); }
};
