import assert from "node:assert/strict";
import test from "node:test";
import Expense from "../models/Expense.js";
import { backfillExpenseNumbers } from "../services/expenseNumberBackfillService.js";
import { createExpenseRecord, validateExpensePayload } from "../services/expenseService.js";
import {
  formatExpenseNumber,
  getRiyadhCreationYear,
  reserveExpenseNumberWithStore,
} from "../services/expenseNumberService.js";

const createMemoryAllocator = (highestByYear = {}) => {
  const counters = new Map();
  const findHighest = async (year) => Number(highestByYear[year] || 0);
  const increment = async ({ counterId, floor }) => {
    const next = Math.max(counters.get(counterId) || 0, floor) + 1;
    counters.set(counterId, next);
    return next;
  };
  return (date) => reserveExpenseNumberWithStore({ date, findHighest, increment });
};

test("expense IDs use the Riyadh creation year and reset their sequence annually", async () => {
  assert.equal(getRiyadhCreationYear(new Date("2026-12-31T20:59:59.000Z")), 2026);
  assert.equal(getRiyadhCreationYear(new Date("2026-12-31T21:00:00.000Z")), 2027);
  assert.equal(formatExpenseNumber(2026, 1), "EXP-2026-000001");
  const allocate = createMemoryAllocator();
  assert.equal((await allocate(new Date("2026-06-01T00:00:00Z"))).expenseNumber, "EXP-2026-000001");
  assert.equal((await allocate(new Date("2026-06-02T00:00:00Z"))).expenseNumber, "EXP-2026-000002");
  assert.equal((await allocate(new Date("2027-01-01T00:00:00Z"))).expenseNumber, "EXP-2027-000001");
});

test("concurrent expense creation receives unique sequential IDs and retries a duplicate", async () => {
  const allocate = createMemoryAllocator({ 2026: 40 });
  const date = new Date("2026-09-27T08:00:00Z");
  const createdNumbers = new Set();
  let injectCollision = true;
  const ExpenseModel = {
    async create(document) {
      if (injectCollision) {
        injectCollision = false;
        throw Object.assign(new Error("duplicate"), { code: 11000, keyPattern: { expenseNumber: 1 }, keyValue: { expenseNumber: document.expenseNumber } });
      }
      if (createdNumbers.has(document.expenseNumber)) {
        throw Object.assign(new Error("duplicate"), { code: 11000, keyPattern: { expenseNumber: 1 }, keyValue: { expenseNumber: document.expenseNumber } });
      }
      createdNumbers.add(document.expenseNumber);
      return document;
    },
  };
  const reserve = ({ date: creationDate }) => allocate(creationDate);
  const rows = await Promise.all(Array.from({ length: 25 }, (_, index) => createExpenseRecord(
    { title: `Expense ${index}` },
    { createdAt: date, reserve, ExpenseModel }
  )));
  assert.equal(new Set(rows.map((row) => row.expenseNumber)).size, 25);
  assert.equal(Math.min(...rows.map((row) => Number(row.expenseNumber.slice(-6)))), 42, "the collided ID is never reused");
  assert.equal(Math.max(...rows.map((row) => Number(row.expenseNumber.slice(-6)))), 66);
});

test("expense IDs are immutable, uniquely indexed, and rejected from client payloads", async () => {
  assert.equal(Expense.schema.path("expenseNumber").options.immutable, true);
  const uniqueIndex = Expense.schema.indexes().find(([keys, options]) => keys.expenseNumber === 1 && options.unique);
  assert.ok(uniqueIndex, "expenseNumber must have a unique index");
  assert.deepEqual(uniqueIndex[1].partialFilterExpression, { expenseNumber: { $type: "string" } });
  await assert.rejects(
    validateExpensePayload({ expenseNumber: "EXP-2026-999999" }, { partial: true, existing: {} }),
    /generated by the server/
  );
});

test("chronological backfill is idempotent and never reuses archived IDs", async () => {
  const rows = [
    { _id: "c", createdAt: new Date("2026-03-01T00:00:00Z"), recordStatus: "active" },
    { _id: "a", createdAt: new Date("2025-01-01T00:00:00Z"), recordStatus: "archived" },
    { _id: "b", createdAt: new Date("2026-02-01T00:00:00Z"), recordStatus: "cancelled" },
  ];
  const ExpenseModel = {
    find() {
      return {
        sort() { return this; },
        select() { return this; },
        async lean() {
          return rows.filter((row) => !row.expenseNumber).sort((left, right) => left.createdAt - right.createdAt || String(left._id).localeCompare(String(right._id)));
        },
      };
    },
    collection: {
      async updateOne(filter, update) {
        const row = rows.find((entry) => entry._id === filter._id);
        if (!row || row.expenseNumber) return { modifiedCount: 0 };
        row.expenseNumber = update.$set.expenseNumber;
        return { modifiedCount: 1 };
      },
    },
  };
  const allocate = createMemoryAllocator();
  const reserve = ({ date }) => allocate(date);
  assert.deepEqual(await backfillExpenseNumbers({ ExpenseModel, reserve }), { scanned: 3, assigned: 3, skipped: 0 });
  assert.equal(rows.find((row) => row._id === "a").expenseNumber, "EXP-2025-000001");
  assert.equal(rows.find((row) => row._id === "b").expenseNumber, "EXP-2026-000001");
  assert.equal(rows.find((row) => row._id === "c").expenseNumber, "EXP-2026-000002");
  assert.deepEqual(await backfillExpenseNumbers({ ExpenseModel, reserve }), { scanned: 0, assigned: 0, skipped: 0 });
});
