"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertTriangle, CheckCircle2, ClipboardCheck, LoaderCircle, Minus, Plus, Search, Trash2, XCircle, Zap } from "lucide-react";
import { toast } from "sonner";
import AdminShell from "../AdminShell.jsx";
import { formatAdminCurrency } from "../adminUi.js";
import DarkDatePicker from "../../ui/DarkDatePicker.jsx";
import SmartImage from "../../SmartImage.jsx";
import { useAuth } from "../../../context/AuthContext.jsx";
import { checkDeliveryOrderDuplicate, createDeliveryOrderEntry, fetchCombos, fetchDeliveryEntryConfig, fetchMenuItems } from "../../../api/api.js";
import DeliveryCustomizationDialog from "./DeliveryCustomizationDialog.jsx";

const PROVIDER_LABELS = { jahez: "Jahez", keeta: "Keeta", hungerstation: "HungerStation", ninja: "Ninja" };
const PROVIDER_COLORS = { jahez: "bg-[#ee3038]", keeta: "bg-[#ffd727] text-black", hungerstation: "bg-[#ffc629] text-black", ninja: "bg-[#15191b]" };
const card = "rounded-2xl border border-white/10 bg-gradient-to-br from-white/[0.045] to-white/[0.015]";
const input = "h-11 w-full rounded-xl border border-white/10 bg-black/25 px-3 text-sm text-white outline-none placeholder:text-neutral-600 focus:border-dune-amber/60";
const localDateTime = (date = new Date()) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
const lineIdentity = (line) => `${line.productType}:${line.productId}:${JSON.stringify(line.customization || {})}`;

const Field = ({ label, error, children }) => <div className="block"><span className="mb-1.5 block text-xs font-medium text-neutral-300">{label}</span>{children}{error && <span className="mt-1 block text-[0.68rem] text-red-400">{error}</span>}</div>;

function EntryDetails({ config, form, setForm, duplicateState, fields }) {
  return <section className={`${card} p-4 sm:p-5`}><h2 className="text-base font-semibold text-white">Delivery Details</h2>
    <fieldset className="mt-4"><legend className="mb-2 text-xs font-medium text-neutral-300">Delivery platform</legend><div className="grid grid-cols-2 gap-2">{(config?.providers || []).map((provider) => <button key={provider.value} type="button" disabled={!provider.enabled} onClick={() => setForm((current) => ({ ...current, provider: provider.value }))} className={`relative flex min-h-16 items-center justify-center rounded-xl border p-2 font-semibold transition ${form.provider === provider.value ? "border-dune-amber ring-1 ring-dune-amber/30" : "border-white/10"} ${PROVIDER_COLORS[provider.value]} disabled:cursor-not-allowed disabled:opacity-35`}>{PROVIDER_LABELS[provider.value]}{form.provider === provider.value && <CheckCircle2 className="absolute bottom-1.5 left-1.5 h-4 w-4" />}</button>)}</div></fieldset>
    <div className="mt-4 space-y-4"><Field label="External Order ID" error={fields.externalOrderId}><div className="relative"><input value={form.externalOrderId} onChange={(event) => setForm((current) => ({ ...current, externalOrderId: event.target.value.toUpperCase() }))} maxLength={100} placeholder="e.g. JHS-784921633" className={`${input} pr-10`} />{duplicateState.loading && <LoaderCircle className="absolute right-3 top-3.5 h-4 w-4 animate-spin text-dune-amber" />}{duplicateState.checked && !duplicateState.duplicate && <CheckCircle2 className="absolute right-3 top-3.5 h-4 w-4 text-emerald-400" />}{duplicateState.duplicate && <XCircle className="absolute right-3 top-3.5 h-4 w-4 text-red-400" />}</div>{duplicateState.duplicate && <p className="mt-2 rounded-lg border border-red-500/20 bg-red-500/[0.07] p-2 text-xs text-red-300">Already saved as #{duplicateState.existingOrder?.orderNumber}</p>}</Field>
      <Field label="Original order date & time" error={fields.orderOccurredAt}><DarkDatePicker type="datetime-local" required max={localDateTime()} value={form.orderOccurredAt} onChange={(event) => setForm((current) => ({ ...current, orderOccurredAt: event.target.value }))} className={input} /></Field>
      <Field label="Branch" error={fields.branch}><input value={form.branch} onChange={(event) => setForm((current) => ({ ...current, branch: event.target.value }))} className={input} /></Field>
      <Field label="Order status"><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setForm((current) => ({ ...current, entryStatus: "completed" }))} className={`h-11 rounded-xl border text-sm font-semibold ${form.entryStatus === "completed" ? "border-emerald-500 bg-emerald-500/10 text-emerald-300" : "border-white/10 text-neutral-400"}`}>Completed</button><button type="button" onClick={() => setForm((current) => ({ ...current, entryStatus: "cancelled" }))} className={`h-11 rounded-xl border text-sm font-semibold ${form.entryStatus === "cancelled" ? "border-red-500 bg-red-500/10 text-red-300" : "border-white/10 text-neutral-400"}`}>Cancelled</button></div></Field>
      <div className="rounded-xl border border-sky-500/20 bg-sky-500/[0.06] p-3 text-xs text-sky-200"><strong>Aggregator prepaid</strong><p className="mt-1 text-sky-200/65">Payment is recorded only; no external payment is initiated.</p></div>
      <Field label="Internal notes (optional)"><textarea value={form.notes} onChange={(event) => setForm((current) => ({ ...current, notes: event.target.value.slice(0, 500) }))} rows={3} className={`${input} h-auto min-h-24 py-3`} /></Field>
    </div>
  </section>;
}

function Catalog({ products, loading, search, setSearch, category, setCategory, onAdd }) {
  const categories = useMemo(() => ["All", ...new Set(products.map((row) => row.productType === "combo" ? "Combos" : row.category).filter(Boolean))], [products]);
  const visible = useMemo(() => { const query = search.trim().toLowerCase(); return products.filter((row) => (category === "All" || (row.productType === "combo" ? "Combos" : row.category) === category) && (!query || row.name.toLowerCase().includes(query) || row.description?.toLowerCase().includes(query))); }, [category, products, search]);
  return <section className={`${card} min-w-0 overflow-hidden`}><div className="border-b border-white/10 p-4"><label className="relative block"><Search className="absolute left-3 top-3.5 h-4 w-4 text-neutral-500" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search menu items…" className={`${input} pl-10`} /></label><div className="mt-3 flex gap-2 overflow-x-auto pb-1">{categories.map((value) => <button key={value} type="button" onClick={() => setCategory(value)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-semibold ${category === value ? "border-dune-amber bg-dune-amber text-black" : "border-white/10 text-neutral-400 hover:border-dune-amber/50"}`}>{value}</button>)}</div></div>
    <div className="max-h-[680px] divide-y divide-white/[0.06] overflow-y-auto">{loading ? <div className="grid min-h-72 place-items-center text-sm text-neutral-500"><LoaderCircle className="h-5 w-5 animate-spin text-dune-amber" /></div> : visible.map((product) => <article key={`${product.productType}-${product._id}`} className="flex items-center gap-3 p-3 hover:bg-white/[0.025]"><SmartImage src={product.image} alt="" width={80} height={80} className="h-14 w-14 rounded-xl object-cover" /><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-semibold text-white">{product.name}</h3><p className="mt-0.5 line-clamp-1 text-xs text-neutral-600">{product.description || product.category}</p></div><strong className="whitespace-nowrap text-sm text-white">{formatAdminCurrency(product.price)}</strong><button type="button" onClick={() => onAdd(product)} className="inline-flex h-10 items-center gap-1 rounded-lg bg-dune-amber px-3 text-xs font-bold text-black"><Plus className="h-4 w-4" />Add</button></article>)}{!loading && !visible.length && <p className="py-20 text-center text-sm text-neutral-600">No matching menu items.</p>}</div>
  </section>;
}

function OrderSummary({ cart, systemTotal, form, setForm, changeQuantity, remove, clear, submitting, save }) {
  const difference = Number(((Number(form.platformTotal) || 0) - systemTotal).toFixed(2));
  return <section className={`${card} overflow-hidden xl:sticky xl:top-20`}><div className="flex items-center justify-between border-b border-white/10 p-4"><h2 className="text-base font-semibold text-white">Order Items</h2><button type="button" onClick={clear} disabled={!cart.length} className="inline-flex items-center gap-1.5 text-xs text-red-400 disabled:opacity-30"><Trash2 className="h-4 w-4" />Clear All</button></div>
    <div className="max-h-[390px] divide-y divide-white/[0.06] overflow-y-auto px-4">{cart.map((line) => <div key={lineIdentity(line)} className="py-4"><div className="flex items-center gap-2"><SmartImage src={line.image} alt="" width={64} height={64} className="h-12 w-12 rounded-lg object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-white">{line.name}</p><p className="text-xs text-neutral-600">{formatAdminCurrency(line.price)} each</p></div><button type="button" onClick={() => changeQuantity(line, -1)} className="rounded border border-white/10 p-1.5 text-neutral-400"><Minus className="h-3 w-3" /></button><span className="w-5 text-center text-xs text-white">{line.quantity}</span><button type="button" onClick={() => changeQuantity(line, 1)} className="rounded border border-white/10 p-1.5 text-neutral-400"><Plus className="h-3 w-3" /></button><button type="button" onClick={() => remove(line)} className="p-1 text-red-400"><Trash2 className="h-4 w-4" /></button></div>{line.customizationLabel && <p className="ml-14 mt-2 text-xs text-neutral-500">{line.customizationLabel}</p>}<p className="mt-2 text-right text-xs font-semibold text-white">{formatAdminCurrency(line.price * line.quantity)}</p></div>)}{!cart.length && <p className="py-16 text-center text-sm text-neutral-600">Add menu items to this delivery order.</p>}</div>
    <div className="space-y-3 border-t border-white/10 p-4"><div className="flex justify-between text-sm text-neutral-400"><span>System total</span><strong className="text-white">{formatAdminCurrency(systemTotal)}</strong></div><Field label="Platform total" error={form.fieldErrors?.platformTotal}><div className="relative"><input type="number" min="0" step="0.01" value={form.platformTotal} onChange={(event) => setForm((current) => ({ ...current, platformTotal: event.target.value }))} className={`${input} pr-14 text-right`} /><span className="absolute right-3 top-3.5 text-xs text-neutral-500">SAR</span></div></Field><div className="flex justify-between border-t border-white/10 pt-3"><span className="text-sm text-neutral-400">Difference</span><strong className={Math.abs(difference) < 0.01 ? "text-emerald-400" : "text-amber-400"}>{difference > 0 ? "+" : ""}{formatAdminCurrency(difference)}</strong></div>
      {Math.abs(difference) >= 0.01 && <Field label="Difference reason" error={form.fieldErrors?.differenceReason}><textarea value={form.differenceReason} onChange={(event) => setForm((current) => ({ ...current, differenceReason: event.target.value.slice(0, 300) }))} placeholder="Explain commission, platform promotion or price variance…" className={`${input} h-auto min-h-20 py-3`} /></Field>}
      {form.entryStatus === "completed" ? <p className="flex gap-2 rounded-xl border border-emerald-500/20 bg-emerald-500/[0.06] p-3 text-xs text-emerald-200"><ClipboardCheck className="h-4 w-4 shrink-0" />Saving will deduct recipe ingredients once and record stock movements.</p> : <p className="flex gap-2 rounded-xl border border-red-500/20 bg-red-500/[0.06] p-3 text-xs text-red-200"><AlertTriangle className="h-4 w-4 shrink-0" />Cancelled entries do not affect revenue or inventory.</p>}
      <div className="grid grid-cols-2 gap-2"><button type="button" disabled={submitting} onClick={() => save(false)} className="h-12 rounded-xl border border-dune-amber text-sm font-semibold text-dune-amber disabled:opacity-40">Save Order</button><button type="button" disabled={submitting} onClick={() => save(true)} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-dune-amber text-sm font-semibold text-black disabled:opacity-40">{submitting ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Zap className="h-4 w-4" />}Save & Add Next</button></div>
    </div>
  </section>;
}

export default function QuickDeliveryOrderPage() {
  const { user, logout } = useAuth();
  const router = useRouter();
  const [config, setConfig] = useState(null); const [catalog, setCatalog] = useState([]); const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState(""); const [category, setCategory] = useState("All"); const [cart, setCart] = useState([]); const [customizing, setCustomizing] = useState(null); const [submitting, setSubmitting] = useState(false);
  const [duplicateState, setDuplicateState] = useState({ loading: false, checked: false, duplicate: false, existingOrder: null });
  const initialForm = (nextConfig = config) => ({ provider: nextConfig?.providers?.find((row) => row.enabled)?.value || "jahez", externalOrderId: "", orderOccurredAt: localDateTime(), branch: nextConfig?.defaultBranch || "", entryStatus: "completed", platformTotal: "", differenceReason: "", notes: "", fieldErrors: {} });
  const [form, setForm] = useState(() => initialForm(null));
  useEffect(() => { Promise.all([fetchDeliveryEntryConfig(), fetchMenuItems(), fetchCombos()]).then(([nextConfig, items, combos]) => { setConfig(nextConfig); setForm(initialForm(nextConfig)); setCatalog([...items.filter((row) => row.isAvailable !== false).map((row) => ({ ...row, productType: "menuItem", price: Number(row.price) })), ...combos.map((row) => ({ ...row, productType: "combo", price: Number(row.comboPrice) }))]); }).catch((error) => toast.error(error.response?.data?.message || "Unable to load delivery order entry." )).finally(() => setLoading(false)); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { const externalOrderId = form.externalOrderId.trim(); if (externalOrderId.length < 2) { setDuplicateState({ loading: false, checked: false, duplicate: false, existingOrder: null }); return undefined; } let active = true; setDuplicateState((current) => ({ ...current, loading: true })); const timeout = setTimeout(() => checkDeliveryOrderDuplicate(form.provider, externalOrderId).then((result) => active && setDuplicateState({ loading: false, checked: true, duplicate: result.duplicate, existingOrder: result.existingOrder })).catch(() => active && setDuplicateState({ loading: false, checked: false, duplicate: false, existingOrder: null })), 350); return () => { active = false; clearTimeout(timeout); }; }, [form.externalOrderId, form.provider]);
  const systemTotal = useMemo(() => Number(cart.reduce((sum, row) => sum + Number(row.price) * row.quantity, 0).toFixed(2)), [cart]);
  const addLine = (line) => { setCart((current) => { const key = lineIdentity(line); const found = current.find((row) => lineIdentity(row) === key); return found ? current.map((row) => lineIdentity(row) === key ? { ...row, quantity: Math.min(99, row.quantity + line.quantity) } : row) : [...current, line]; }); setCustomizing(null); };
  const addProduct = (product) => { if (product.productType === "menuItem" && product.customization?.enabled) setCustomizing(product); else addLine({ productId: product._id, productType: product.productType, name: product.name, image: product.image, price: product.price, quantity: 1, customization: {}, customizationLabel: "" }); };
  const changeQuantity = (target, amount) => setCart((rows) => rows.map((row) => lineIdentity(row) === lineIdentity(target) ? { ...row, quantity: row.quantity + amount } : row).filter((row) => row.quantity > 0));
  const reset = (retainContext) => { setCart([]); setSearch(""); setCategory("All"); setDuplicateState({ loading: false, checked: false, duplicate: false, existingOrder: null }); setForm((current) => ({ ...initialForm(config), ...(retainContext ? { provider: current.provider, branch: current.branch } : {}) })); };
  const save = async (addNext) => { const difference = Number(((Number(form.platformTotal) || 0) - systemTotal).toFixed(2)); const fieldErrors = {}; if (!form.externalOrderId.trim()) fieldErrors.externalOrderId = "Required"; if (!form.orderOccurredAt) fieldErrors.orderOccurredAt = "Required"; if (!form.branch.trim()) fieldErrors.branch = "Required"; if (form.platformTotal === "" || Number(form.platformTotal) < 0) fieldErrors.platformTotal = "Enter the platform total"; if (Math.abs(difference) >= 0.01 && !form.differenceReason.trim()) fieldErrors.differenceReason = "Explain the total difference"; setForm((current) => ({ ...current, fieldErrors })); if (Object.keys(fieldErrors).length || !cart.length || duplicateState.duplicate) { toast.error(!cart.length ? "Add at least one menu item." : duplicateState.duplicate ? `Already saved as #${duplicateState.existingOrder?.orderNumber}.` : "Check the highlighted fields."); return; } setSubmitting(true); try { const order = await createDeliveryOrderEntry({ provider: form.provider, externalOrderId: form.externalOrderId, orderOccurredAt: form.orderOccurredAt, branch: form.branch, entryStatus: form.entryStatus, platformTotal: Number(form.platformTotal), differenceReason: form.differenceReason, notes: form.notes, items: cart.map((row) => ({ productId: row.productId, productType: row.productType, quantity: row.quantity, customization: row.customization })) }); toast.success(`Delivery order #${order.orderNumber} saved.`); reset(addNext); } catch (error) { const fields = error.response?.data?.fields || {}; setForm((current) => ({ ...current, fieldErrors: fields })); if (error.response?.data?.existingOrder) setDuplicateState({ loading: false, checked: true, duplicate: true, existingOrder: error.response.data.existingOrder }); toast.error(error.response?.data?.message || "Unable to save the delivery order."); } finally { setSubmitting(false); } };
  const navigate = (tab) => { if (tab === "quick-delivery") return; router.push(tab === "pos" ? "/pos" : `/admin?tab=${tab}`); };
  return <AdminShell activeTab="quick-delivery" onTabChange={navigate} title="Quick Delivery Order" subtitle="Enter completed or cancelled orders from delivery partner history." user={user} onLogout={logout} dashboard={null} searchQuery="" onSearchChange={() => {}} searchResults={[]} searching={false} showGlobalSearch={false} showOrderControls={false} showSidebarUserCard>
    <div className="grid items-start gap-4 xl:grid-cols-[350px_minmax(420px,1fr)_390px]"><EntryDetails config={config} form={form} setForm={setForm} duplicateState={duplicateState} fields={form.fieldErrors || {}} /><Catalog products={catalog} loading={loading} search={search} setSearch={setSearch} category={category} setCategory={setCategory} onAdd={addProduct} /><OrderSummary cart={cart} systemTotal={systemTotal} form={form} setForm={setForm} changeQuantity={changeQuantity} remove={(target) => setCart((rows) => rows.filter((row) => lineIdentity(row) !== lineIdentity(target)))} clear={() => cart.length && window.confirm("Clear all order items?") && setCart([])} submitting={submitting} save={save} /></div>
    {customizing && <DeliveryCustomizationDialog product={customizing} onClose={() => setCustomizing(null)} onAdd={addLine} />}
  </AdminShell>;
}
