"use client";

import { LoaderCircle, Trash2, X } from "lucide-react";
import { useEffect } from "react";

export default function PosHeldSalesDrawer({ open, loading, sales, onClose, onResume, onCancel }) {
  useEffect(() => { if (!open) return undefined; const close = (event) => event.key === "Escape" && onClose(); document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [open, onClose]);
  if (!open) return null;
  return <div className="fixed inset-0 z-[105] flex justify-end bg-black/70" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><aside role="dialog" aria-modal="true" aria-label="Held sales" className="h-full w-full max-w-lg overflow-y-auto border-l border-white/10 bg-[#0d1113] p-5"><div className="flex items-center justify-between"><div><p className="text-[0.65rem] uppercase tracking-widest text-dune-amber">POS recovery</p><h2 className="mt-1 text-xl font-semibold text-white">Held Sales</h2></div><button type="button" onClick={onClose} className="grid h-11 w-11 place-items-center rounded-xl border border-white/10" aria-label="Close held sales"><X className="h-5 w-5" /></button></div>{loading ? <div className="grid min-h-48 place-items-center"><LoaderCircle className="h-6 w-6 animate-spin text-dune-amber" /></div> : <div className="mt-5 space-y-3">{sales.map((row) => <article key={row._id} className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><div className="flex justify-between gap-4"><div><h3 className="font-semibold text-white">{row.label || row.customer?.name || "Untitled sale"}</h3><p className="mt-1 text-xs text-neutral-500">{row.items?.length || 0} lines · {row.cashier?.name || "Cashier"} · {new Date(row.updatedAt).toLocaleString()}</p></div><span className="text-sm font-semibold text-dune-amber">Held</span></div><div className="mt-4 grid grid-cols-[1fr_auto] gap-2"><button type="button" onClick={() => onResume(row)} className="min-h-11 rounded-xl bg-dune-amber font-semibold text-black">Resume</button><button type="button" onClick={() => onCancel(row)} className="grid h-11 w-11 place-items-center rounded-xl border border-red-500/25 text-red-400" aria-label="Cancel held sale"><Trash2 className="h-4 w-4" /></button></div></article>)}{!sales.length && <p className="py-16 text-center text-sm text-neutral-500">No held sales.</p>}</div>}</aside></div>;
}
