"use client";

import { Plus, Search } from "lucide-react";
import SmartImage from "../../SmartImage.jsx";
import { formatAdminCurrency } from "../adminUi.js";

export default function PosProductGrid({ products, categories, search, onSearchChange, category, onCategoryChange, onAdd, loading }) {
  return <section>
    <div className="mb-4 flex flex-col gap-3 lg:flex-row lg:items-center">
      <label className="relative w-full lg:max-w-xs"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-500" /><input type="search" value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search menu items…" className="h-11 w-full rounded-xl border border-white/10 bg-[#0d1113] pl-10 pr-3 text-sm text-white outline-none placeholder:text-neutral-600 focus:border-dune-amber/60" /></label>
      <div className="flex gap-2 overflow-x-auto pb-1">{categories.map((value) => <button key={value} type="button" onClick={() => onCategoryChange(value)} className={`whitespace-nowrap rounded-xl border px-4 py-2.5 text-xs font-semibold transition ${category === value ? "border-dune-amber bg-dune-amber text-black" : "border-white/10 bg-white/[0.025] text-neutral-300 hover:border-dune-amber/40 hover:text-dune-amber"}`}>{value}</button>)}</div>
    </div>
    <p className="mb-3 text-[0.68rem] font-semibold uppercase tracking-[0.18em] text-neutral-500">Menu Items</p>
    {loading ? <div className="grid min-h-72 place-items-center rounded-2xl border border-white/10 bg-white/[0.02] text-sm text-neutral-500">Loading POS catalog…</div> : products.length ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 2xl:grid-cols-4">{products.map((product) => <article key={`${product.productType}-${product._id}`} className="group overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-white/[0.055] to-white/[0.018] transition hover:-translate-y-0.5 hover:border-dune-amber/45"><button type="button" onClick={() => onAdd(product)} className="block w-full text-left"><div className="relative aspect-[1.5] overflow-hidden bg-black/30"><SmartImage src={product.image} alt={product.name} fill sizes="(max-width: 640px) 50vw, 240px" className="object-cover transition duration-300 group-hover:scale-105" /><span className="absolute right-2 top-2 rounded-full border border-black/20 bg-black/75 px-2 py-1 text-[0.6rem] font-semibold text-dune-amber">{product.productType === "combo" ? "COMBO" : product.category}</span></div><div className="flex items-end justify-between gap-2 p-3"><div className="min-w-0"><h3 className="truncate text-sm font-medium text-white">{product.name}</h3><p className="mt-1 text-xs font-semibold text-neutral-400">{formatAdminCurrency(product.price)}</p>{product.productType === "combo" && <p className="mt-1 line-clamp-1 text-[0.62rem] text-neutral-600">{(product.items || []).map((line) => `${line.menuItem?.name} ×${line.quantity}`).join(", ")}</p>}</div><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full border border-dune-amber text-dune-amber transition group-hover:bg-dune-amber group-hover:text-black"><Plus className="h-4 w-4" /></span></div></button></article>)}</div> : <div className="grid min-h-72 place-items-center rounded-2xl border border-white/10 bg-white/[0.02] text-center"><div><Search className="mx-auto h-8 w-8 text-neutral-700" /><p className="mt-3 text-sm text-neutral-400">No products match this filter.</p></div></div>}
  </section>;
}
