"use client";

import { Printer, X } from "lucide-react";
import { formatAdminCurrency, formatAdminDate } from "../adminUi.js";

const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character]);

const printReceipt = (sale) => {
  const popup = window.open("", "_blank", "width=420,height=720");
  if (!popup) return;
  const itemRows = (sale.items || []).map((item) => `<tr><td>${escapeHtml(item.name)} ×${item.quantity}</td><td>${escapeHtml(formatAdminCurrency(item.price * item.quantity))}</td></tr>`).join("");
  popup.document.write(`<!doctype html><html><head><title>Receipt ${escapeHtml(sale.orderNumber)}</title><style>body{font:14px system-ui;margin:24px;color:#111}h1{text-align:center;font-size:20px}p{text-align:center;color:#555}table{width:100%;border-collapse:collapse;margin:20px 0}td{padding:8px 0;border-bottom:1px dashed #bbb}td:last-child{text-align:right}.total{font-size:18px;font-weight:700}.meta{display:flex;justify-content:space-between;margin:6px 0}.thanks{margin-top:24px}</style></head><body><h1>DUNE &amp; GRILLS</h1><p>POS SALES RECEIPT</p><div class="meta"><span>Order</span><strong>#${escapeHtml(sale.orderNumber)}</strong></div><div class="meta"><span>Date</span><span>${escapeHtml(formatAdminDate(sale.createdAt, { hour: "2-digit", minute: "2-digit" }))}</span></div><div class="meta"><span>Cashier</span><span>${escapeHtml(sale.createdBy?.name || "—")}</span></div><div class="meta"><span>Order type</span><span>${escapeHtml(sale.orderType)}</span></div><table>${itemRows}<tr><td>Subtotal</td><td>${escapeHtml(formatAdminCurrency(sale.subtotal))}</td></tr>${Number(sale.discountAmount) ? `<tr><td>Discount</td><td>-${escapeHtml(formatAdminCurrency(sale.discountAmount))}</td></tr>` : ""}<tr class="total"><td>Total</td><td>${escapeHtml(formatAdminCurrency(sale.totalAmount))}</td></tr></table><div class="meta"><span>Payment</span><span>${escapeHtml(sale.paymentMethod)}</span></div>${sale.paymentMethod === "cash" ? `<div class="meta"><span>Cash received</span><span>${escapeHtml(formatAdminCurrency(sale.cashReceived))}</span></div><div class="meta"><span>Change</span><span>${escapeHtml(formatAdminCurrency(sale.changeDue))}</span></div>` : ""}<p class="thanks">Thank you for visiting Dune &amp; Grills.</p><script>window.onload=()=>{window.print();}</script></body></html>`);
  popup.document.close();
};

export default function PosReceiptDialog({ sale, onClose }) {
  if (!sale) return null;
  return <div className="fixed inset-0 z-[90] grid place-items-center overflow-y-auto bg-black/80 p-4 backdrop-blur-sm" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#121719] p-5 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[0.65rem] uppercase tracking-[0.2em] text-dune-amber">Sale completed</p><h2 className="mt-1 text-xl font-semibold text-white">Receipt #{sale.orderNumber}</h2></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-neutral-500 hover:bg-white/5 hover:text-white"><X className="h-4 w-4" /></button></div><div className="mt-5 space-y-3 border-y border-dashed border-white/15 py-4">{sale.items.map((item, index) => <div key={`${item.name}-${index}`} className="flex justify-between gap-4 text-sm"><span className="text-neutral-300">{item.name} ×{item.quantity}</span><span className="text-white">{formatAdminCurrency(item.price * item.quantity)}</span></div>)}</div><div className="mt-4 space-y-2 text-sm"><div className="flex justify-between text-neutral-400"><span>Subtotal</span><span>{formatAdminCurrency(sale.subtotal)}</span></div>{Number(sale.discountAmount) > 0 && <div className="flex justify-between text-emerald-400"><span>Discount</span><span>-{formatAdminCurrency(sale.discountAmount)}</span></div>}<div className="flex justify-between border-t border-white/10 pt-3 text-lg font-semibold"><span className="text-white">Total</span><span className="text-dune-amber">{formatAdminCurrency(sale.totalAmount)}</span></div>{sale.paymentMethod === "cash" && <><div className="flex justify-between text-neutral-400"><span>Cash received</span><span>{formatAdminCurrency(sale.cashReceived)}</span></div><div className="flex justify-between text-emerald-400"><span>Change</span><span>{formatAdminCurrency(sale.changeDue)}</span></div></>}</div><button type="button" onClick={() => printReceipt(sale)} className="mt-5 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-dune-amber font-semibold text-black"><Printer className="h-4 w-4" />Print Receipt</button></div></div>;
}
