"use client";

import { Clock3, Printer } from "lucide-react";
import { formatAdminCurrency, formatAdminDate } from "../adminUi.js";

const summarizeItems = (items = []) => items.map((item) => `${item.name} ×${item.quantity}`).join(", ");

export default function PosRecentSales({ sales, loading, onReceipt }) {
  return <section className="mt-5 overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br from-white/[0.045] to-white/[0.015]"><div className="flex items-center gap-2 border-b border-white/10 px-4 py-3"><Clock3 className="h-4 w-4 text-dune-amber" /><h2 className="text-sm font-semibold text-white">Recent POS Sales</h2></div>{loading ? <p className="p-6 text-sm text-neutral-500">Loading recent sales…</p> : <div className="overflow-x-auto"><table className="min-w-full text-left text-xs"><thead className="border-b border-white/10 text-[0.65rem] uppercase tracking-wider text-neutral-600"><tr><th className="px-4 py-3">Order</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Items</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Time</th><th className="px-4 py-3">Cashier</th><th className="px-4 py-3" /></tr></thead><tbody className="divide-y divide-white/[0.06]">{sales.map((sale) => <tr key={sale._id} className="hover:bg-white/[0.025]"><td className="whitespace-nowrap px-4 py-3 font-medium text-white">#{sale.orderNumber}</td><td className="whitespace-nowrap px-4 py-3 capitalize text-neutral-300">{sale.orderType}</td><td className="max-w-md truncate px-4 py-3 text-neutral-400">{summarizeItems(sale.items)}</td><td className="whitespace-nowrap px-4 py-3 font-medium text-dune-amber">{formatAdminCurrency(sale.totalAmount)}</td><td className="whitespace-nowrap px-4 py-3 capitalize text-neutral-300">{sale.paymentMethod}</td><td className="whitespace-nowrap px-4 py-3 text-neutral-500">{formatAdminDate(sale.createdAt, { hour: "2-digit", minute: "2-digit" })}</td><td className="whitespace-nowrap px-4 py-3 text-neutral-300">{sale.createdBy?.name || "—"}</td><td className="px-4 py-3 text-right"><button type="button" onClick={() => onReceipt(sale)} className="rounded-lg p-2 text-neutral-500 hover:bg-white/5 hover:text-dune-amber" aria-label={`Print receipt ${sale.orderNumber}`}><Printer className="h-4 w-4" /></button></td></tr>)}{!sales.length && <tr><td colSpan={8} className="p-8 text-center text-neutral-600">No POS sales have been completed yet.</td></tr>}</tbody></table></div>}</section>;
}
