"use client";

import { Banknote, CheckCircle2, CreditCard, LoaderCircle, Minus, Plus, Trash2, UserRound, X } from "lucide-react";
import SmartImage from "../../SmartImage.jsx";
import { formatAdminCurrency } from "../adminUi.js";

const Choice = ({ active, onClick, icon: Icon, children }) => <button type="button" onClick={onClick} className={`flex min-h-11 flex-1 items-center justify-center gap-2 rounded-xl border px-3 text-sm font-medium transition ${active ? "border-dune-amber bg-dune-amber/10 text-dune-amber" : "border-white/10 bg-white/[0.025] text-neutral-400 hover:text-white"}`}><Icon className="h-4 w-4" />{children}</button>;

export default function PosSalePanel({ sale, onQuantity, onRemove, onClear, notes, onNotesChange, discount, onDiscountChange, discountReason, onDiscountReasonChange, orderType, onOrderTypeChange, paymentMethod, onPaymentMethodChange, cashReceived, onCashReceivedChange, customerSearch, onCustomerSearchChange, customerResults, selectedCustomer, onSelectCustomer, onClearCustomer, onComplete, submitting }) {
  const subtotal = sale.reduce((sum, line) => sum + Number(line.price) * line.quantity, 0);
  const safeDiscount = Math.min(Math.max(Number(discount) || 0, 0), subtotal);
  const total = Math.max(0, subtotal - safeDiscount);
  const change = paymentMethod === "cash" ? Math.max(0, (Number(cashReceived) || 0) - total) : 0;
  const cashValid = paymentMethod !== "cash" || Number(cashReceived) >= total;
  return <aside className="rounded-2xl border border-white/10 bg-gradient-to-br from-[#121719] to-[#0b0e10] p-4 shadow-2xl shadow-black/30 xl:sticky xl:top-20 xl:max-h-[calc(100vh-6rem)] xl:overflow-y-auto">
    <div className="flex items-center justify-between border-b border-white/10 pb-3"><h2 className="text-sm font-semibold uppercase tracking-wide text-white">Current Sale</h2><button type="button" disabled={!sale.length} onClick={onClear} className="inline-flex items-center gap-1.5 rounded-lg border border-red-500/20 px-3 py-2 text-xs text-red-400 hover:bg-red-500/10 disabled:opacity-40"><Trash2 className="h-3.5 w-3.5" />Clear Sale</button></div>
    <div className="max-h-60 divide-y divide-white/[0.06] overflow-y-auto">{sale.map((line) => <div key={`${line.productType}-${line.productId}`} className="flex items-center gap-2 py-3"><SmartImage src={line.image} alt="" width={56} height={56} sizes="40px" className="h-10 w-10 rounded-lg object-cover" /><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-white">{line.name}</p><p className="mt-0.5 text-[0.65rem] text-neutral-500">{formatAdminCurrency(line.price)} each</p></div><div className="flex items-center rounded-lg border border-white/10"><button type="button" onClick={() => onQuantity(line, -1)} className="p-1.5 text-neutral-400 hover:text-white"><Minus className="h-3 w-3" /></button><span className="min-w-6 text-center text-xs text-white">{line.quantity}</span><button type="button" onClick={() => onQuantity(line, 1)} className="p-1.5 text-neutral-400 hover:text-white"><Plus className="h-3 w-3" /></button></div><p className="w-16 text-right text-xs font-medium text-white">{formatAdminCurrency(line.price * line.quantity)}</p><button type="button" onClick={() => onRemove(line)} className="p-1.5 text-red-400" aria-label={`Remove ${line.name}`}><X className="h-3.5 w-3.5" /></button></div>)}{!sale.length && <p className="py-10 text-center text-xs text-neutral-600">Add a menu item to start a sale.</p>}</div>
    <div className="mt-3"><div className="relative"><UserRound className="absolute left-3 top-3 h-4 w-4 text-neutral-600" />{selectedCustomer ? <div className="flex h-11 items-center rounded-xl border border-emerald-500/20 bg-emerald-500/[0.06] pl-10 pr-2 text-sm"><span className="min-w-0 flex-1 truncate text-emerald-300">{selectedCustomer.name} · {selectedCustomer.phone || selectedCustomer.email}</span><button type="button" onClick={onClearCustomer} className="p-2 text-neutral-500 hover:text-white"><X className="h-4 w-4" /></button></div> : <input value={customerSearch} onChange={(event) => onCustomerSearchChange(event.target.value)} placeholder="Optional customer search…" className="h-11 w-full rounded-xl border border-white/10 bg-black/25 pl-10 pr-3 text-sm text-white outline-none placeholder:text-neutral-600 focus:border-dune-amber/60" />}{!selectedCustomer && customerResults.length > 0 && <div className="absolute z-30 mt-1 max-h-44 w-full overflow-y-auto rounded-xl border border-white/10 bg-[#15191b] p-1 shadow-xl">{customerResults.map((customer) => <button key={customer._id} type="button" onClick={() => onSelectCustomer(customer)} className="block w-full rounded-lg px-3 py-2 text-left hover:bg-white/5"><span className="block text-xs font-medium text-white">{customer.name}</span><span className="text-[0.65rem] text-neutral-500">{customer.phone || customer.email}</span></button>)}</div>}</div></div>
    <textarea value={notes} onChange={(event) => onNotesChange(event.target.value)} maxLength={500} placeholder="Order / customer note (optional)" className="mt-3 min-h-16 w-full resize-y rounded-xl border border-white/10 bg-black/25 p-3 text-xs text-white outline-none placeholder:text-neutral-600 focus:border-dune-amber/60" />
    <div className="mt-3 space-y-2 border-y border-white/10 py-3 text-sm"><div className="flex justify-between text-neutral-400"><span>Subtotal</span><span>{formatAdminCurrency(subtotal)}</span></div><div className="grid grid-cols-[1fr_110px] items-center gap-2 text-neutral-400"><label htmlFor="pos-discount">Discount</label><input id="pos-discount" type="number" min="0" max={subtotal} step="0.01" value={discount} onChange={(event) => onDiscountChange(event.target.value)} className="h-9 rounded-lg border border-white/10 bg-black/30 px-2 text-right text-sm text-white outline-none focus:border-dune-amber/60" /></div>{Number(discount) > 0 && <input value={discountReason} maxLength={160} onChange={(event) => onDiscountReasonChange(event.target.value)} placeholder="Discount reason" className="h-9 w-full rounded-lg border border-white/10 bg-black/30 px-3 text-xs text-white outline-none placeholder:text-neutral-600" />}<div className="flex justify-between border-t border-white/10 pt-3 text-lg font-semibold"><span className="text-white">Total</span><span className="text-dune-amber">{formatAdminCurrency(total)}</span></div></div>
    <div className="mt-4"><p className="mb-2 text-[0.65rem] font-semibold uppercase tracking-wider text-neutral-500">Order Type</p><div className="flex gap-2"><Choice active={orderType === "dine-in"} onClick={() => onOrderTypeChange("dine-in")} icon={CheckCircle2}>Dine-in</Choice><Choice active={orderType === "takeaway"} onClick={() => onOrderTypeChange("takeaway")} icon={CheckCircle2}>Takeaway</Choice></div></div>
    <div className="mt-4"><p className="mb-2 text-[0.65rem] font-semibold uppercase tracking-wider text-neutral-500">Payment Method</p><div className="grid grid-cols-3 gap-2"><Choice active={paymentMethod === "cash"} onClick={() => onPaymentMethodChange("cash")} icon={Banknote}>Cash</Choice><Choice active={paymentMethod === "card"} onClick={() => onPaymentMethodChange("card")} icon={CreditCard}>Card</Choice><Choice active={paymentMethod === "other"} onClick={() => onPaymentMethodChange("other")} icon={CreditCard}>Other</Choice></div></div>
    {paymentMethod === "cash" && <div className="mt-3 grid grid-cols-2 gap-3 rounded-xl border border-white/10 bg-black/20 p-3"><label className="text-xs text-neutral-500">Received amount<input type="number" min="0" step="0.01" value={cashReceived} onChange={(event) => onCashReceivedChange(event.target.value)} className="mt-1 h-9 w-full rounded-lg border border-white/10 bg-black/30 px-2 text-white outline-none focus:border-dune-amber/60" /></label><div className="text-xs text-neutral-500">Change<p className={`mt-2 text-base font-semibold ${cashValid ? "text-emerald-400" : "text-red-400"}`}>{formatAdminCurrency(change)}</p></div></div>}
    <button type="button" onClick={onComplete} disabled={submitting || !sale.length || !cashValid} className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-dune-amberDeep to-dune-amber font-semibold text-black shadow-amberGlow transition hover:brightness-110 disabled:cursor-not-allowed disabled:opacity-45">{submitting ? <LoaderCircle className="h-5 w-5 animate-spin" /> : <CheckCircle2 className="h-5 w-5" />}Complete Sale</button>
  </aside>;
}
