"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Boxes, ClipboardList, ShieldCheck, TrendingUp } from "lucide-react";
import { toast } from "sonner";
import { completePosSale, fetchAdminUsers, fetchAllMenuItems, fetchCombos, fetchPosSales } from "@/src/api/api.js";
import PosProductGrid from "./PosProductGrid.jsx";
import PosRecentSales from "./PosRecentSales.jsx";
import PosReceiptDialog from "./PosReceiptDialog.jsx";
import PosSalePanel from "./PosSalePanel.jsx";

export default function PosTab({ onSaleCompleted }) {
  const [catalog, setCatalog] = useState([]); const [catalogLoading, setCatalogLoading] = useState(true);
  const [search, setSearch] = useState(""); const [category, setCategory] = useState("All");
  const [sale, setSale] = useState([]); const [notes, setNotes] = useState(""); const [discount, setDiscount] = useState(""); const [discountReason, setDiscountReason] = useState("");
  const [orderType, setOrderType] = useState("dine-in"); const [paymentMethod, setPaymentMethod] = useState("cash"); const [cashReceived, setCashReceived] = useState("");
  const [customerSearch, setCustomerSearch] = useState(""); const [customerResults, setCustomerResults] = useState([]); const [selectedCustomer, setSelectedCustomer] = useState(null);
  const [submitting, setSubmitting] = useState(false); const [recentSales, setRecentSales] = useState([]); const [recentLoading, setRecentLoading] = useState(true); const [receipt, setReceipt] = useState(null);
  const requestKey = useRef("");
  const loadRecent = async () => { setRecentLoading(true); try { setRecentSales(await fetchPosSales({ limit: 10 })); } catch { toast.error("Unable to load recent POS sales."); } finally { setRecentLoading(false); } };
  useEffect(() => { Promise.all([fetchAllMenuItems(), fetchCombos()]).then(([menuItems, combos]) => setCatalog([...menuItems.filter((item) => item.isAvailable).map((item) => ({ ...item, productType: "menuItem", price: Number(item.price) })), ...combos.map((combo) => ({ ...combo, productType: "combo", price: Number(combo.comboPrice) }))])).catch(() => toast.error("Unable to load the POS catalog.")).finally(() => setCatalogLoading(false)); loadRecent(); }, []);
  useEffect(() => { const query = customerSearch.trim(); if (query.length < 2 || selectedCustomer) { setCustomerResults([]); return undefined; } let active = true; const timeout = setTimeout(() => fetchAdminUsers("customers", query).then((rows) => active && setCustomerResults(rows.slice(0, 8))).catch(() => active && setCustomerResults([])), 250); return () => { active = false; clearTimeout(timeout); }; }, [customerSearch, selectedCustomer]);
  const categories = useMemo(() => ["All", ...new Set(catalog.map((item) => item.productType === "combo" ? "Combos" : item.category).filter(Boolean))], [catalog]);
  const filteredProducts = useMemo(() => { const query = search.trim().toLowerCase(); return catalog.filter((product) => (category === "All" || (product.productType === "combo" ? "Combos" : product.category) === category) && (!query || product.name.toLowerCase().includes(query) || product.category?.toLowerCase().includes(query))); }, [catalog, category, search]);
  const addProduct = (product) => setSale((current) => { const index = current.findIndex((line) => line.productId === product._id && line.productType === product.productType); if (index < 0) return [...current, { productId: product._id, productType: product.productType, name: product.name, image: product.image, price: product.price, quantity: 1 }]; return current.map((line, lineIndex) => lineIndex === index ? { ...line, quantity: Math.min(99, line.quantity + 1) } : line); });
  const changeQuantity = (target, amount) => setSale((current) => current.map((line) => line.productId === target.productId && line.productType === target.productType ? { ...line, quantity: line.quantity + amount } : line).filter((line) => line.quantity > 0));
  const remove = (target) => setSale((current) => current.filter((line) => !(line.productId === target.productId && line.productType === target.productType)));
  const resetSale = () => { setSale([]); setNotes(""); setDiscount(""); setDiscountReason(""); setCashReceived(""); setSelectedCustomer(null); setCustomerSearch(""); requestKey.current = ""; };
  const clearSale = () => { if (sale.length && window.confirm("Clear every item from the current sale?")) resetSale(); };
  const complete = async () => { setSubmitting(true); try { if (!requestKey.current) requestKey.current = window.crypto.randomUUID(); const response = await completePosSale({ idempotencyKey: requestKey.current, items: sale.map(({ productId, productType, quantity }) => ({ productId, productType, quantity })), orderType, paymentMethod, cashReceived: paymentMethod === "cash" ? Number(cashReceived) : undefined, discountAmount: Number(discount || 0), discountReason, notes, customerId: selectedCustomer?._id }); setReceipt(response.data); if (response.warning) toast.warning(response.warning); else toast.success(`Sale #${response.data.orderNumber} completed.`); resetSale(); await loadRecent(); onSaleCompleted?.(); } catch (error) { toast.error(error.response?.data?.message || error.response?.data?.error || "Unable to complete sale."); } finally { setSubmitting(false); } };
  return <div><div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_390px]"><PosProductGrid products={filteredProducts} categories={categories} search={search} onSearchChange={setSearch} category={category} onCategoryChange={setCategory} onAdd={addProduct} loading={catalogLoading} /><PosSalePanel sale={sale} onQuantity={changeQuantity} onRemove={remove} onClear={clearSale} notes={notes} onNotesChange={setNotes} discount={discount} onDiscountChange={setDiscount} discountReason={discountReason} onDiscountReasonChange={setDiscountReason} orderType={orderType} onOrderTypeChange={setOrderType} paymentMethod={paymentMethod} onPaymentMethodChange={setPaymentMethod} cashReceived={cashReceived} onCashReceivedChange={setCashReceived} customerSearch={customerSearch} onCustomerSearchChange={setCustomerSearch} customerResults={customerResults} selectedCustomer={selectedCustomer} onSelectCustomer={(customer) => { setSelectedCustomer(customer); setCustomerResults([]); setCustomerSearch(""); }} onClearCustomer={() => setSelectedCustomer(null)} onComplete={complete} submitting={submitting} /></div><PosRecentSales sales={recentSales} loading={recentLoading} onReceipt={setReceipt} /><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[Boxes, "Inventory Auto Deduction", "Stock movements are created from recipe ingredients."], [ClipboardList, "Recipe Based", "Combos expand into their existing menu item recipes."], [TrendingUp, "Sales Reporting", "POS orders are included in the existing order totals."], [ShieldCheck, "Secure & Reliable", "Prices, discounts and payments are validated server-side."]].map(([Icon, title, text]) => <article key={title} className="rounded-2xl border border-white/10 bg-white/[0.025] p-4"><div className="flex gap-3"><span className="rounded-xl bg-dune-amber/10 p-2 text-dune-amber"><Icon className="h-5 w-5" /></span><div><h3 className="text-sm font-semibold text-dune-amber">{title}</h3><p className="mt-1 text-xs leading-5 text-neutral-500">{text}</p></div></div></article>)}</div><PosReceiptDialog sale={receipt} onClose={() => setReceipt(null)} /></div>;
}
