"use client";

import { useCallback, useEffect, useState } from "react";
import { Archive, Download, Pencil, Plus, Search, XCircle } from "lucide-react";
import { toast } from "sonner";
import DarkSelect from "@/src/components/ui/DarkSelect.jsx";
import DarkDatePicker from "@/src/components/ui/DarkDatePicker.jsx";
import { archiveExpense, createExpense, exportExpenses, fetchExpenseCategories, fetchExpenses, updateExpense } from "@/src/api/financeApi.js";
import { Badge, Button, DataTable, EmptyState, LoadingState, Modal, Pagination, cardClass, inputClass } from "@/src/components/inventory/InventoryUI.jsx";
import { downloadCsv } from "@/src/components/inventory/inventoryUtils.js";
import ExpenseForm from "./ExpenseForm.jsx";
import { errorMessage, formatDate, formatSar, humanize, statusTone } from "./financeUtils.js";

export default function ExpenseEntries({ canManage, initialAdd = false }) {
  const [data, setData] = useState(null); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(true);
  const [filters, setFilters] = useState({ search: "", category: "", paymentStatus: "", vendor: "", recurring: "", from: "", to: "", page: 1 });
  const [open, setOpen] = useState(initialAdd); const [editing, setEditing] = useState(null); const [submitting, setSubmitting] = useState(false);
  const load = useCallback(async () => { const params = { ...filters, limit: 15, category: filters.category || undefined, paymentStatus: filters.paymentStatus || undefined, recurring: filters.recurring || undefined, from: filters.from || undefined, to: filters.to || undefined, search: filters.search || undefined, vendor: filters.vendor || undefined }; setLoading(true); try { const [rows, cats] = await Promise.all([fetchExpenses(params), fetchExpenseCategories(true)]); setData(rows); setCategories(cats); } catch (error) { toast.error(errorMessage(error)); } finally { setLoading(false); } }, [filters]);
  useEffect(() => { const timer = setTimeout(load, 180); return () => clearTimeout(timer); }, [load]);
  const setFilter = (field, value) => setFilters((current) => ({ ...current, [field]: value, page: field === "page" ? value : 1 }));
  const save = async (payload) => { setSubmitting(true); try { if (editing) await updateExpense(editing._id, payload); else await createExpense(payload); toast.success(editing ? "Expense updated." : "Expense added."); setOpen(false); setEditing(null); await load(); } catch (error) { toast.error(errorMessage(error)); } finally { setSubmitting(false); } };
  const archive = async (row) => { if (!window.confirm(`Archive ${row.title}? Historical totals and audit history will be preserved.`)) return; try { await archiveExpense(row._id, { reason: "Archived from expense entries" }); toast.success("Expense archived."); load(); } catch (error) { toast.error(errorMessage(error)); } };
  const cancel = async (row) => { const reason = window.prompt(`Why is ${row.title} being cancelled?`); if (reason == null) return; if (!reason.trim()) return toast.error("A cancellation reason is required."); try { await archiveExpense(row._id, { recordStatus: "cancelled", reason }); toast.success("Expense cancelled; its audit history was preserved."); load(); } catch (error) { toast.error(errorMessage(error)); } };
  const exportCsv = async () => { try { const result = await exportExpenses({ ...filters, page: undefined, limit: undefined }); downloadCsv(`operating-expenses-${new Date().toISOString().slice(0, 10)}.csv`, [["Date", (row) => row.expenseDate], ["Title", (row) => row.title], ["Category", (row) => row.category?.name], ["Vendor", (row) => row.vendor], ["Reference", (row) => row.referenceNumber], ["Total SAR", (row) => row.totalAmount], ["VAT SAR", (row) => row.vatAmount], ["Paid SAR", (row) => row.amountPaid], ["Payment status", (row) => row.paymentStatus], ["Recurring", (row) => Boolean(row.recurringTemplate)]], result.data); } catch (error) { toast.error(errorMessage(error)); } };
  const columns = [
    { key: "date", label: "Date", render: (row) => formatDate(row.expenseDate) },
    { key: "title", label: "Expense", render: (row) => <div className="max-w-64"><p className="truncate font-medium text-white" title={row.title}>{row.title}</p><p className="truncate text-[0.68rem] text-neutral-600" title={row.vendor}>{row.vendor || row.referenceNumber || "One-time expense"}</p></div> },
    { key: "category", label: "Category", render: (row) => row.category?.name || "Archived category" },
    { key: "amount", label: "Amount", render: (row) => formatSar(row.totalAmount) },
    { key: "paid", label: "Paid", render: (row) => formatSar(row.amountPaid) },
    { key: "status", label: "Status", render: (row) => <Badge tone={statusTone(row.paymentStatus)}>{humanize(row.paymentStatus)}</Badge> },
    { key: "type", label: "Type", render: (row) => row.recurringTemplate ? "Recurring" : "One-time" },
    { key: "actions", label: "", render: (row) => canManage && <div className="flex justify-end gap-1"><button type="button" onClick={() => { setEditing(row); setOpen(true); }} className="rounded-lg p-2 text-neutral-500 hover:bg-white/5 hover:text-white" aria-label={`Edit ${row.title}`}><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => cancel(row)} className="rounded-lg p-2 text-neutral-500 hover:bg-red-500/10 hover:text-red-300" aria-label={`Cancel ${row.title}`} title="Cancel expense"><XCircle className="h-4 w-4" /></button><button type="button" onClick={() => archive(row)} className="rounded-lg p-2 text-neutral-500 hover:bg-red-500/10 hover:text-red-300" aria-label={`Archive ${row.title}`} title="Archive expense"><Archive className="h-4 w-4" /></button></div> },
  ];
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold text-white">Expense Entries</h2><p className="text-xs text-neutral-500">Operating expenses only; inventory purchase orders are intentionally excluded.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={exportCsv}><Download className="h-4 w-4" />Export CSV</Button>{canManage && <Button onClick={() => { setEditing(null); setOpen(true); }}><Plus className="h-4 w-4" />Add Expense</Button>}</div></div>
    <section className={cardClass}><div className="grid gap-3 border-b border-white/10 p-4 sm:grid-cols-2 xl:grid-cols-4"><label className="relative xl:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-neutral-600" /><input className={`${inputClass} pl-10`} value={filters.search} onChange={(event) => setFilter("search", event.target.value)} placeholder="Search title, reference or vendor…" /></label><DarkSelect className={inputClass} value={filters.category} onChange={(event) => setFilter("category", event.target.value)}><option value="">All categories</option>{categories.map((row) => <option key={row._id} value={row._id}>{row.name}</option>)}</DarkSelect><DarkSelect className={inputClass} value={filters.paymentStatus} onChange={(event) => setFilter("paymentStatus", event.target.value)}><option value="">All payment states</option><option value="unpaid">Unpaid</option><option value="partially_paid">Partially paid</option><option value="paid">Paid</option></DarkSelect><input className={inputClass} value={filters.vendor} onChange={(event) => setFilter("vendor", event.target.value)} placeholder="Vendor / payee" /><DarkSelect className={inputClass} value={filters.recurring} onChange={(event) => setFilter("recurring", event.target.value)}><option value="">All expense types</option><option value="false">One-time</option><option value="true">Recurring</option></DarkSelect><DarkDatePicker aria-label="From date" className={inputClass} value={filters.from} onChange={(event) => setFilter("from", event.target.value)} /><DarkDatePicker aria-label="To date" className={inputClass} value={filters.to} onChange={(event) => setFilter("to", event.target.value)} /></div>
      {loading ? <LoadingState label="Loading expenses…" /> : <DataTable columns={columns} rows={data?.data} empty={<EmptyState title="No expenses found" description="Change the filters or add the first operating expense." />} />}<Pagination pagination={data?.pagination} onPageChange={(page) => setFilter("page", page)} />
    </section>
    <Modal open={open} onClose={() => { setOpen(false); setEditing(null); }} title={editing ? "Edit expense" : "Add expense"} description="Amounts and payment status are validated by the server." maxWidth="max-w-3xl"><ExpenseForm expense={editing} categories={categories} onSubmit={save} submitting={submitting} /></Modal>
  </div>;
}
