"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CalendarClock, CircleDollarSign, Plus, ReceiptText, Repeat2 } from "lucide-react";
import { toast } from "sonner";
import DarkDatePicker from "@/src/components/ui/DarkDatePicker.jsx";
import { createExpense, fetchExpenseCategories, fetchExpenseDashboard } from "@/src/api/financeApi.js";
import { Badge, Button, EmptyState, LoadingState, Modal, StatCard, cardClass, inputClass } from "@/src/components/inventory/InventoryUI.jsx";
import ExpenseForm from "./ExpenseForm.jsx";
import { errorMessage, formatDate, formatSar, humanize, monthRange, statusTone } from "./financeUtils.js";

export default function FinanceDashboard({ canManage }) {
  const [range, setRange] = useState(monthRange); const [data, setData] = useState(null); const [categories, setCategories] = useState([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [submitting, setSubmitting] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const [dashboard, cats] = await Promise.all([fetchExpenseDashboard(range), fetchExpenseCategories()]); setData(dashboard); setCategories(cats); } catch (error) { toast.error(errorMessage(error)); } finally { setLoading(false); } }, [range]);
  useEffect(() => { load(); }, [load]);
  const maxTrend = useMemo(() => Math.max(1, ...(data?.trend || []).map((row) => Number(row.total))), [data]);
  const save = async (payload) => { setSubmitting(true); try { await createExpense(payload); toast.success("Expense added."); setOpen(false); load(); } catch (error) { toast.error(errorMessage(error)); } finally { setSubmitting(false); } };
  if (loading) return <div className={cardClass}><LoadingState label="Loading finance dashboard…" /></div>;
  if (!data) return <EmptyState title="Finance dashboard unavailable" action={<Button onClick={load}>Try again</Button>} />;
  const summary = data.summary;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-3"><div className="grid grid-cols-2 gap-2"><DarkDatePicker aria-label="Range start" className={inputClass} value={range.from} onChange={(event) => setRange((current) => ({ ...current, from: event.target.value }))} /><DarkDatePicker aria-label="Range end" className={inputClass} value={range.to} onChange={(event) => setRange((current) => ({ ...current, to: event.target.value }))} /></div>{canManage && <Button onClick={() => setOpen(true)}><Plus className="h-4 w-4" />Add Expense</Button>}</div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Selected Period Expenses" value={formatSar(summary.totalExpenses)} caption={summary.changePercent == null ? "No comparable prior period" : `${summary.changePercent >= 0 ? "+" : ""}${summary.changePercent}% vs previous period`} icon={CircleDollarSign} /><StatCard label="Paid Expenses" value={formatSar(summary.paidAmount)} caption={`${summary.paidCount} fully paid bills`} icon={ReceiptText} tone="green" /><StatCard label="Unpaid Bills" value={formatSar(summary.outstandingAmount)} caption={`${summary.unpaidCount} open or partial bills`} icon={CalendarClock} tone="red" /><StatCard label="Recurring Expenses" value={formatSar(summary.activeRecurringAmount)} caption={`${summary.activeRecurringCount} active templates`} icon={Repeat2} tone="amber" /></div>
    <div className="grid gap-5 xl:grid-cols-[1.55fr_1fr]"><section className={`${cardClass} p-5`}><h2 className="font-semibold text-white">Monthly Operating Expenses</h2><p className="mt-1 text-xs text-neutral-600">Inventory purchases and COGS are not included.</p><div className="mt-6 flex h-64 items-end gap-3 border-b border-white/10 px-2">{data.trend.length ? data.trend.map((row) => <div key={row.month} className="flex h-full min-w-0 flex-1 flex-col justify-end"><p className="mb-2 truncate text-center text-[0.65rem] text-neutral-500">{formatSar(row.total)}</p><div className="mx-auto w-full max-w-20 rounded-t-lg bg-gradient-to-t from-amber-700 to-dune-amber" style={{ height: `${Math.max(5, Number(row.total) / maxTrend * 78)}%` }} /><p className="mt-2 text-center text-[0.65rem] text-neutral-500">{row.month}</p></div>) : <div className="m-auto text-sm text-neutral-600">No expenses in this period.</div>}</div></section><section className={`${cardClass} p-5`}><h2 className="font-semibold text-white">Category Breakdown</h2><div className="mt-5 space-y-4">{data.categoryBreakdown.length ? data.categoryBreakdown.map((row) => <div key={row._id}><div className="mb-1.5 flex items-center justify-between gap-3 text-xs"><span className="flex min-w-0 items-center gap-2 text-neutral-300"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{ backgroundColor: row.color }} /><span className="truncate">{row.name}</span></span><span>{formatSar(row.total)}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full" style={{ width: `${summary.totalExpenses ? Math.max(2, row.total / summary.totalExpenses * 100) : 0}%`, backgroundColor: row.color }} /></div></div>) : <p className="text-sm text-neutral-600">No category totals yet.</p>}</div></section></div>
    <div className="grid gap-5 xl:grid-cols-2"><section className={cardClass}><div className="border-b border-white/10 p-4"><h2 className="font-semibold text-white">Recent Expenses</h2></div><div className="divide-y divide-white/[0.06]">{data.recentExpenses.map((row) => <div key={row._id} className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="truncate text-sm text-white">{row.title}</p><p className="mt-1 text-xs text-neutral-600">{row.category?.name} · {formatDate(row.expenseDate)}</p></div><div className="text-right"><p className="text-sm">{formatSar(row.totalAmount)}</p><Badge tone={statusTone(row.paymentStatus)}>{humanize(row.paymentStatus)}</Badge></div></div>)}{!data.recentExpenses.length && <EmptyState title="No recent expenses" />}</div></section><section className={cardClass}><div className="border-b border-white/10 p-4"><h2 className="font-semibold text-white">Upcoming Recurring Bills</h2></div><div className="divide-y divide-white/[0.06]">{data.upcomingRecurring.map((row) => <div key={row._id} className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="truncate text-sm text-white">{row.title}</p><p className="mt-1 text-xs text-neutral-600">{humanize(row.frequency)} · due {formatDate(row.nextDueDate)}</p></div><p className="text-sm">{formatSar(row.defaultAmount)}</p></div>)}{!data.upcomingRecurring.length && <EmptyState title="No upcoming recurring bills" />}</div></section></div>
    <Modal open={open} onClose={() => setOpen(false)} title="Add expense" description="General operating expenses only—not inventory purchase receipts." maxWidth="max-w-3xl"><ExpenseForm categories={categories} onSubmit={save} submitting={submitting} /></Modal>
  </div>;
}
